language: python
python:
  - 2.7
  - 3.3
matrix:
  include:
    - python: 2.7
      env: TESTMODE=full
before_install:
  - pip install nose
  - pip install numpy
  - pip install scipy
  - pip install cDecimal
  - pip install psutil
  - pip install PyQt4
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - python -V
  - popd
script: nosetests
notifications:
  email: false
