# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Sebastian\Mis documentos\Programacion\Proyectos\IA2013TPIRL\gui\qt\IA2013TPIRLGUI\gwopcionesdialog.ui'
#
# Created: Thu May 30 00:07:16 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GWOpcionesDialog(object):
    def setupUi(self, GWOpcionesDialog):
        GWOpcionesDialog.setObjectName(_fromUtf8("GWOpcionesDialog"))
        GWOpcionesDialog.resize(775, 496)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/Configurar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GWOpcionesDialog.setWindowIcon(icon)
        GWOpcionesDialog.setSizeGripEnabled(True)
        GWOpcionesDialog.setModal(True)
        self.gridLayout_2 = QtGui.QGridLayout(GWOpcionesDialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gbEstados = QtGui.QGroupBox(GWOpcionesDialog)
        self.gbEstados.setObjectName(_fromUtf8("gbEstados"))
        self.gridLayout_16 = QtGui.QGridLayout(self.gbEstados)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.gbEstadoBueno = QtGui.QGroupBox(self.gbEstados)
        self.gbEstadoBueno.setObjectName(_fromUtf8("gbEstadoBueno"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gbEstadoBueno)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_21 = QtGui.QLabel(self.gbEstadoBueno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(70, 0))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_22.addWidget(self.label_21)
        self.txtBuenoNombre = QtGui.QLineEdit(self.gbEstadoBueno)
        self.txtBuenoNombre.setObjectName(_fromUtf8("txtBuenoNombre"))
        self.horizontalLayout_22.addWidget(self.txtBuenoNombre)
        self.gridLayout_9.addLayout(self.horizontalLayout_22, 0, 0, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_22 = QtGui.QLabel(self.gbEstadoBueno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(70, 0))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_23.addWidget(self.label_22)
        self.txtBuenoLetra = QtGui.QLineEdit(self.gbEstadoBueno)
        self.txtBuenoLetra.setObjectName(_fromUtf8("txtBuenoLetra"))
        self.horizontalLayout_23.addWidget(self.txtBuenoLetra)
        self.gridLayout_9.addLayout(self.horizontalLayout_23, 1, 0, 1, 1)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_23 = QtGui.QLabel(self.gbEstadoBueno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(70, 0))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_24.addWidget(self.label_23)
        self.txtBuenoColor = QtGui.QLineEdit(self.gbEstadoBueno)
        self.txtBuenoColor.setObjectName(_fromUtf8("txtBuenoColor"))
        self.horizontalLayout_24.addWidget(self.txtBuenoColor)
        self.btnElegirColorBueno = QtGui.QToolButton(self.gbEstadoBueno)
        self.btnElegirColorBueno.setObjectName(_fromUtf8("btnElegirColorBueno"))
        self.horizontalLayout_24.addWidget(self.btnElegirColorBueno)
        self.gridLayout_9.addLayout(self.horizontalLayout_24, 2, 0, 1, 1)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_24 = QtGui.QLabel(self.gbEstadoBueno)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(70, 0))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_25.addWidget(self.label_24)
        self.sbBuenoRecompensa = QtGui.QSpinBox(self.gbEstadoBueno)
        self.sbBuenoRecompensa.setObjectName(_fromUtf8("sbBuenoRecompensa"))
        self.horizontalLayout_25.addWidget(self.sbBuenoRecompensa)
        self.gridLayout_9.addLayout(self.horizontalLayout_25, 3, 0, 1, 1)
        self.gridLayout_16.addWidget(self.gbEstadoBueno, 0, 1, 1, 1)
        self.gbEstadoNeutro = QtGui.QGroupBox(self.gbEstados)
        self.gbEstadoNeutro.setObjectName(_fromUtf8("gbEstadoNeutro"))
        self.gridLayout_13 = QtGui.QGridLayout(self.gbEstadoNeutro)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.label_36 = QtGui.QLabel(self.gbEstadoNeutro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setMinimumSize(QtCore.QSize(70, 0))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_37.addWidget(self.label_36)
        self.txtNeutroNombre = QtGui.QLineEdit(self.gbEstadoNeutro)
        self.txtNeutroNombre.setObjectName(_fromUtf8("txtNeutroNombre"))
        self.horizontalLayout_37.addWidget(self.txtNeutroNombre)
        self.gridLayout_13.addLayout(self.horizontalLayout_37, 0, 0, 1, 1)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        self.label_37 = QtGui.QLabel(self.gbEstadoNeutro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setMinimumSize(QtCore.QSize(70, 0))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_38.addWidget(self.label_37)
        self.txtNeutroLetra = QtGui.QLineEdit(self.gbEstadoNeutro)
        self.txtNeutroLetra.setObjectName(_fromUtf8("txtNeutroLetra"))
        self.horizontalLayout_38.addWidget(self.txtNeutroLetra)
        self.gridLayout_13.addLayout(self.horizontalLayout_38, 1, 0, 1, 1)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.label_38 = QtGui.QLabel(self.gbEstadoNeutro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setMinimumSize(QtCore.QSize(70, 0))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_39.addWidget(self.label_38)
        self.txtNeutroColor = QtGui.QLineEdit(self.gbEstadoNeutro)
        self.txtNeutroColor.setObjectName(_fromUtf8("txtNeutroColor"))
        self.horizontalLayout_39.addWidget(self.txtNeutroColor)
        self.btnElegirColorNeutro = QtGui.QToolButton(self.gbEstadoNeutro)
        self.btnElegirColorNeutro.setObjectName(_fromUtf8("btnElegirColorNeutro"))
        self.horizontalLayout_39.addWidget(self.btnElegirColorNeutro)
        self.gridLayout_13.addLayout(self.horizontalLayout_39, 2, 0, 1, 1)
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        self.label_39 = QtGui.QLabel(self.gbEstadoNeutro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setMinimumSize(QtCore.QSize(70, 0))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_40.addWidget(self.label_39)
        self.sbNeutroRecompensa = QtGui.QSpinBox(self.gbEstadoNeutro)
        self.sbNeutroRecompensa.setObjectName(_fromUtf8("sbNeutroRecompensa"))
        self.horizontalLayout_40.addWidget(self.sbNeutroRecompensa)
        self.gridLayout_13.addLayout(self.horizontalLayout_40, 3, 0, 1, 1)
        self.gridLayout_16.addWidget(self.gbEstadoNeutro, 0, 2, 1, 1)
        self.gbEstadoPared = QtGui.QGroupBox(self.gbEstados)
        self.gbEstadoPared.setObjectName(_fromUtf8("gbEstadoPared"))
        self.gridLayout_12 = QtGui.QGridLayout(self.gbEstadoPared)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.label_40 = QtGui.QLabel(self.gbEstadoPared)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setMinimumSize(QtCore.QSize(70, 0))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_41.addWidget(self.label_40)
        self.txtParedNombre = QtGui.QLineEdit(self.gbEstadoPared)
        self.txtParedNombre.setObjectName(_fromUtf8("txtParedNombre"))
        self.horizontalLayout_41.addWidget(self.txtParedNombre)
        self.gridLayout_12.addLayout(self.horizontalLayout_41, 0, 0, 1, 1)
        self.horizontalLayout_42 = QtGui.QHBoxLayout()
        self.horizontalLayout_42.setObjectName(_fromUtf8("horizontalLayout_42"))
        self.label_41 = QtGui.QLabel(self.gbEstadoPared)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setMinimumSize(QtCore.QSize(70, 0))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_42.addWidget(self.label_41)
        self.txtParedLetra = QtGui.QLineEdit(self.gbEstadoPared)
        self.txtParedLetra.setObjectName(_fromUtf8("txtParedLetra"))
        self.horizontalLayout_42.addWidget(self.txtParedLetra)
        self.gridLayout_12.addLayout(self.horizontalLayout_42, 1, 0, 1, 1)
        self.horizontalLayout_43 = QtGui.QHBoxLayout()
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        self.label_42 = QtGui.QLabel(self.gbEstadoPared)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setMinimumSize(QtCore.QSize(70, 0))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.horizontalLayout_43.addWidget(self.label_42)
        self.txtParedColor = QtGui.QLineEdit(self.gbEstadoPared)
        self.txtParedColor.setObjectName(_fromUtf8("txtParedColor"))
        self.horizontalLayout_43.addWidget(self.txtParedColor)
        self.btnElegirColorPared = QtGui.QToolButton(self.gbEstadoPared)
        self.btnElegirColorPared.setObjectName(_fromUtf8("btnElegirColorPared"))
        self.horizontalLayout_43.addWidget(self.btnElegirColorPared)
        self.gridLayout_12.addLayout(self.horizontalLayout_43, 2, 0, 1, 1)
        self.gridLayout_16.addWidget(self.gbEstadoPared, 1, 2, 1, 1)
        self.gbEstadoExcelente = QtGui.QGroupBox(self.gbEstados)
        self.gbEstadoExcelente.setObjectName(_fromUtf8("gbEstadoExcelente"))
        self.gridLayout_10 = QtGui.QGridLayout(self.gbEstadoExcelente)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_16 = QtGui.QLabel(self.gbEstadoExcelente)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(70, 0))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_17.addWidget(self.label_16)
        self.txtExcelenteNombre = QtGui.QLineEdit(self.gbEstadoExcelente)
        self.txtExcelenteNombre.setObjectName(_fromUtf8("txtExcelenteNombre"))
        self.horizontalLayout_17.addWidget(self.txtExcelenteNombre)
        self.gridLayout_10.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_17 = QtGui.QLabel(self.gbEstadoExcelente)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(70, 0))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_18.addWidget(self.label_17)
        self.txtExcelenteLetra = QtGui.QLineEdit(self.gbEstadoExcelente)
        self.txtExcelenteLetra.setObjectName(_fromUtf8("txtExcelenteLetra"))
        self.horizontalLayout_18.addWidget(self.txtExcelenteLetra)
        self.gridLayout_10.addLayout(self.horizontalLayout_18, 1, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_18 = QtGui.QLabel(self.gbEstadoExcelente)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(70, 0))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_19.addWidget(self.label_18)
        self.txtExcelenteColor = QtGui.QLineEdit(self.gbEstadoExcelente)
        self.txtExcelenteColor.setObjectName(_fromUtf8("txtExcelenteColor"))
        self.horizontalLayout_19.addWidget(self.txtExcelenteColor)
        self.btnElegirColorExcelente = QtGui.QToolButton(self.gbEstadoExcelente)
        self.btnElegirColorExcelente.setObjectName(_fromUtf8("btnElegirColorExcelente"))
        self.horizontalLayout_19.addWidget(self.btnElegirColorExcelente)
        self.gridLayout_10.addLayout(self.horizontalLayout_19, 2, 0, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_20 = QtGui.QLabel(self.gbEstadoExcelente)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(70, 0))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_21.addWidget(self.label_20)
        self.sbExcelenteRecompensa = QtGui.QSpinBox(self.gbEstadoExcelente)
        self.sbExcelenteRecompensa.setObjectName(_fromUtf8("sbExcelenteRecompensa"))
        self.horizontalLayout_21.addWidget(self.sbExcelenteRecompensa)
        self.gridLayout_10.addLayout(self.horizontalLayout_21, 3, 0, 1, 1)
        self.gridLayout_16.addWidget(self.gbEstadoExcelente, 1, 0, 1, 1)
        self.gbEstadoFinal = QtGui.QGroupBox(self.gbEstados)
        self.gbEstadoFinal.setObjectName(_fromUtf8("gbEstadoFinal"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gbEstadoFinal)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_13 = QtGui.QLabel(self.gbEstadoFinal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(70, 0))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_14.addWidget(self.label_13)
        self.txtFinalNombre = QtGui.QLineEdit(self.gbEstadoFinal)
        self.txtFinalNombre.setObjectName(_fromUtf8("txtFinalNombre"))
        self.horizontalLayout_14.addWidget(self.txtFinalNombre)
        self.gridLayout_8.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_14 = QtGui.QLabel(self.gbEstadoFinal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(70, 0))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_15.addWidget(self.label_14)
        self.txtFinalLetra = QtGui.QLineEdit(self.gbEstadoFinal)
        self.txtFinalLetra.setObjectName(_fromUtf8("txtFinalLetra"))
        self.horizontalLayout_15.addWidget(self.txtFinalLetra)
        self.gridLayout_8.addLayout(self.horizontalLayout_15, 1, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_15 = QtGui.QLabel(self.gbEstadoFinal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(70, 0))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_16.addWidget(self.label_15)
        self.txtFinalColor = QtGui.QLineEdit(self.gbEstadoFinal)
        self.txtFinalColor.setObjectName(_fromUtf8("txtFinalColor"))
        self.horizontalLayout_16.addWidget(self.txtFinalColor)
        self.btnElegirColorFinal = QtGui.QToolButton(self.gbEstadoFinal)
        self.btnElegirColorFinal.setObjectName(_fromUtf8("btnElegirColorFinal"))
        self.horizontalLayout_16.addWidget(self.btnElegirColorFinal)
        self.gridLayout_8.addLayout(self.horizontalLayout_16, 2, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_19 = QtGui.QLabel(self.gbEstadoFinal)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(70, 0))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_20.addWidget(self.label_19)
        self.sbFinalRecompensa = QtGui.QSpinBox(self.gbEstadoFinal)
        self.sbFinalRecompensa.setMaximum(1000000000)
        self.sbFinalRecompensa.setObjectName(_fromUtf8("sbFinalRecompensa"))
        self.horizontalLayout_20.addWidget(self.sbFinalRecompensa)
        self.gridLayout_8.addLayout(self.horizontalLayout_20, 3, 0, 1, 1)
        self.gridLayout_16.addWidget(self.gbEstadoFinal, 0, 0, 1, 1)
        self.gbEstadoMalo = QtGui.QGroupBox(self.gbEstados)
        self.gbEstadoMalo.setObjectName(_fromUtf8("gbEstadoMalo"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gbEstadoMalo)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_29 = QtGui.QLabel(self.gbEstadoMalo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(70, 0))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_30.addWidget(self.label_29)
        self.txtMaloNombre = QtGui.QLineEdit(self.gbEstadoMalo)
        self.txtMaloNombre.setObjectName(_fromUtf8("txtMaloNombre"))
        self.horizontalLayout_30.addWidget(self.txtMaloNombre)
        self.gridLayout_11.addLayout(self.horizontalLayout_30, 0, 0, 1, 1)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_30 = QtGui.QLabel(self.gbEstadoMalo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(70, 0))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_31.addWidget(self.label_30)
        self.txtMaloLetra = QtGui.QLineEdit(self.gbEstadoMalo)
        self.txtMaloLetra.setObjectName(_fromUtf8("txtMaloLetra"))
        self.horizontalLayout_31.addWidget(self.txtMaloLetra)
        self.gridLayout_11.addLayout(self.horizontalLayout_31, 1, 0, 1, 1)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.label_31 = QtGui.QLabel(self.gbEstadoMalo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(70, 0))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_32.addWidget(self.label_31)
        self.txtMaloColor = QtGui.QLineEdit(self.gbEstadoMalo)
        self.txtMaloColor.setObjectName(_fromUtf8("txtMaloColor"))
        self.horizontalLayout_32.addWidget(self.txtMaloColor)
        self.btnElegirColorMalo = QtGui.QToolButton(self.gbEstadoMalo)
        self.btnElegirColorMalo.setObjectName(_fromUtf8("btnElegirColorMalo"))
        self.horizontalLayout_32.addWidget(self.btnElegirColorMalo)
        self.gridLayout_11.addLayout(self.horizontalLayout_32, 2, 0, 1, 1)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.label_32 = QtGui.QLabel(self.gbEstadoMalo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMinimumSize(QtCore.QSize(70, 0))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_33.addWidget(self.label_32)
        self.sbMaloRecompensa = QtGui.QSpinBox(self.gbEstadoMalo)
        self.sbMaloRecompensa.setObjectName(_fromUtf8("sbMaloRecompensa"))
        self.horizontalLayout_33.addWidget(self.sbMaloRecompensa)
        self.gridLayout_11.addLayout(self.horizontalLayout_33, 3, 0, 1, 1)
        self.gridLayout_16.addWidget(self.gbEstadoMalo, 1, 1, 1, 1)
        self.gbEstadoInicial = QtGui.QGroupBox(self.gbEstados)
        self.gbEstadoInicial.setObjectName(_fromUtf8("gbEstadoInicial"))
        self.gridLayout_14 = QtGui.QGridLayout(self.gbEstadoInicial)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_2 = QtGui.QLabel(self.gbEstadoInicial)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(70, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.txtInicialNombre = QtGui.QLineEdit(self.gbEstadoInicial)
        self.txtInicialNombre.setObjectName(_fromUtf8("txtInicialNombre"))
        self.horizontalLayout_8.addWidget(self.txtInicialNombre)
        self.gridLayout_14.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_8 = QtGui.QLabel(self.gbEstadoInicial)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(70, 0))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_9.addWidget(self.label_8)
        self.txtInicialLetra = QtGui.QLineEdit(self.gbEstadoInicial)
        self.txtInicialLetra.setObjectName(_fromUtf8("txtInicialLetra"))
        self.horizontalLayout_9.addWidget(self.txtInicialLetra)
        self.gridLayout_14.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_9 = QtGui.QLabel(self.gbEstadoInicial)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(70, 0))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.txtInicialColor = QtGui.QLineEdit(self.gbEstadoInicial)
        self.txtInicialColor.setObjectName(_fromUtf8("txtInicialColor"))
        self.horizontalLayout_10.addWidget(self.txtInicialColor)
        self.btnElegirColorInicial = QtGui.QToolButton(self.gbEstadoInicial)
        self.btnElegirColorInicial.setObjectName(_fromUtf8("btnElegirColorInicial"))
        self.horizontalLayout_10.addWidget(self.btnElegirColorInicial)
        self.gridLayout_14.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)
        self.gridLayout_16.addWidget(self.gbEstadoInicial, 2, 0, 1, 1)
        self.gbEstadoAgente = QtGui.QGroupBox(self.gbEstados)
        self.gbEstadoAgente.setObjectName(_fromUtf8("gbEstadoAgente"))
        self.gridLayout_15 = QtGui.QGridLayout(self.gbEstadoAgente)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.label_33 = QtGui.QLabel(self.gbEstadoAgente)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setMinimumSize(QtCore.QSize(70, 0))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_34.addWidget(self.label_33)
        self.txtAgenteNombre = QtGui.QLineEdit(self.gbEstadoAgente)
        self.txtAgenteNombre.setObjectName(_fromUtf8("txtAgenteNombre"))
        self.horizontalLayout_34.addWidget(self.txtAgenteNombre)
        self.gridLayout_15.addLayout(self.horizontalLayout_34, 0, 0, 1, 1)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.label_34 = QtGui.QLabel(self.gbEstadoAgente)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setMinimumSize(QtCore.QSize(70, 0))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_35.addWidget(self.label_34)
        self.txtAgenteLetra = QtGui.QLineEdit(self.gbEstadoAgente)
        self.txtAgenteLetra.setObjectName(_fromUtf8("txtAgenteLetra"))
        self.horizontalLayout_35.addWidget(self.txtAgenteLetra)
        self.gridLayout_15.addLayout(self.horizontalLayout_35, 1, 0, 1, 1)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.label_35 = QtGui.QLabel(self.gbEstadoAgente)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setMinimumSize(QtCore.QSize(70, 0))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_36.addWidget(self.label_35)
        self.txtAgenteColor = QtGui.QLineEdit(self.gbEstadoAgente)
        self.txtAgenteColor.setObjectName(_fromUtf8("txtAgenteColor"))
        self.horizontalLayout_36.addWidget(self.txtAgenteColor)
        self.btnElegirColorAgente = QtGui.QToolButton(self.gbEstadoAgente)
        self.btnElegirColorAgente.setObjectName(_fromUtf8("btnElegirColorAgente"))
        self.horizontalLayout_36.addWidget(self.btnElegirColorAgente)
        self.gridLayout_15.addLayout(self.horizontalLayout_36, 2, 0, 1, 1)
        self.gridLayout_16.addWidget(self.gbEstadoAgente, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem, 2, 2, 1, 1)
        self.gridLayout_2.addWidget(self.gbEstados, 0, 1, 6, 2)
        self.gbFormato = QtGui.QGroupBox(GWOpcionesDialog)
        self.gbFormato.setObjectName(_fromUtf8("gbFormato"))
        self.gridLayout = QtGui.QGridLayout(self.gbFormato)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.gbFormato)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.sbGWEstadoSize = QtGui.QSpinBox(self.gbFormato)
        self.sbGWEstadoSize.setMinimum(20)
        self.sbGWEstadoSize.setMaximum(100)
        self.sbGWEstadoSize.setProperty("value", 40)
        self.sbGWEstadoSize.setObjectName(_fromUtf8("sbGWEstadoSize"))
        self.horizontalLayout.addWidget(self.sbGWEstadoSize)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gbFormato, 0, 0, 1, 1)
        self.gbRecorrido = QtGui.QGroupBox(GWOpcionesDialog)
        self.gbRecorrido.setObjectName(_fromUtf8("gbRecorrido"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gbRecorrido)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gbRecShowActualState = QtGui.QGroupBox(self.gbRecorrido)
        self.gbRecShowActualState.setFlat(True)
        self.gbRecShowActualState.setCheckable(True)
        self.gbRecShowActualState.setObjectName(_fromUtf8("gbRecShowActualState"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gbRecShowActualState)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.optRecMostrarColorFondo = QtGui.QRadioButton(self.gbRecShowActualState)
        self.optRecMostrarColorFondo.setMinimumSize(QtCore.QSize(140, 0))
        self.optRecMostrarColorFondo.setChecked(True)
        self.optRecMostrarColorFondo.setObjectName(_fromUtf8("optRecMostrarColorFondo"))
        self.horizontalLayout_7.addWidget(self.optRecMostrarColorFondo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.optRecMostrarIcono = QtGui.QRadioButton(self.gbRecShowActualState)
        self.optRecMostrarIcono.setObjectName(_fromUtf8("optRecMostrarIcono"))
        self.verticalLayout_2.addWidget(self.optRecMostrarIcono)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.gbRecShowActualState, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gbRecorrido, 2, 0, 1, 1)
        self.line = QtGui.QFrame(GWOpcionesDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 8, 0, 1, 3)
        self.btnAceptar = QtGui.QPushButton(GWOpcionesDialog)
        self.btnAceptar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnAceptar.setDefault(True)
        self.btnAceptar.setObjectName(_fromUtf8("btnAceptar"))
        self.gridLayout_2.addWidget(self.btnAceptar, 9, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 6, 1, 1, 1)
        self.gbEntrenamiento = QtGui.QGroupBox(GWOpcionesDialog)
        self.gbEntrenamiento.setObjectName(_fromUtf8("gbEntrenamiento"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gbEntrenamiento)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gbEntShowActualState = QtGui.QGroupBox(self.gbEntrenamiento)
        self.gbEntShowActualState.setFlat(True)
        self.gbEntShowActualState.setCheckable(True)
        self.gbEntShowActualState.setObjectName(_fromUtf8("gbEntShowActualState"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gbEntShowActualState)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.optEntMostrarColorFondo = QtGui.QRadioButton(self.gbEntShowActualState)
        self.optEntMostrarColorFondo.setMinimumSize(QtCore.QSize(140, 0))
        self.optEntMostrarColorFondo.setChecked(True)
        self.optEntMostrarColorFondo.setObjectName(_fromUtf8("optEntMostrarColorFondo"))
        self.horizontalLayout_2.addWidget(self.optEntMostrarColorFondo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.optEntMostrarIcono = QtGui.QRadioButton(self.gbEntShowActualState)
        self.optEntMostrarIcono.setObjectName(_fromUtf8("optEntMostrarIcono"))
        self.verticalLayout.addWidget(self.optEntMostrarIcono)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.gbEntShowActualState, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gbEntrenamiento, 1, 0, 1, 1)
        self.label_21.setBuddy(self.txtBuenoNombre)
        self.label_22.setBuddy(self.txtBuenoLetra)
        self.label_23.setBuddy(self.txtBuenoColor)
        self.label_24.setBuddy(self.sbBuenoRecompensa)
        self.label_36.setBuddy(self.txtNeutroNombre)
        self.label_37.setBuddy(self.txtNeutroLetra)
        self.label_38.setBuddy(self.txtNeutroColor)
        self.label_39.setBuddy(self.sbNeutroRecompensa)
        self.label_40.setBuddy(self.txtParedNombre)
        self.label_41.setBuddy(self.txtParedLetra)
        self.label_42.setBuddy(self.txtParedColor)
        self.label_16.setBuddy(self.txtExcelenteNombre)
        self.label_17.setBuddy(self.txtExcelenteLetra)
        self.label_18.setBuddy(self.txtExcelenteColor)
        self.label_20.setBuddy(self.sbExcelenteRecompensa)
        self.label_13.setBuddy(self.txtFinalNombre)
        self.label_14.setBuddy(self.txtFinalLetra)
        self.label_15.setBuddy(self.txtFinalColor)
        self.label_19.setBuddy(self.sbFinalRecompensa)
        self.label_29.setBuddy(self.txtMaloNombre)
        self.label_30.setBuddy(self.txtMaloLetra)
        self.label_31.setBuddy(self.txtMaloColor)
        self.label_32.setBuddy(self.sbMaloRecompensa)
        self.label_2.setBuddy(self.txtInicialNombre)
        self.label_8.setBuddy(self.txtInicialLetra)
        self.label_9.setBuddy(self.txtInicialColor)
        self.label_33.setBuddy(self.txtAgenteNombre)
        self.label_34.setBuddy(self.txtAgenteLetra)
        self.label_35.setBuddy(self.txtAgenteColor)
        self.label.setBuddy(self.sbGWEstadoSize)

        self.retranslateUi(GWOpcionesDialog)
        QtCore.QObject.connect(self.btnAceptar, QtCore.SIGNAL(_fromUtf8("clicked()")), GWOpcionesDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(GWOpcionesDialog)
        GWOpcionesDialog.setTabOrder(self.sbGWEstadoSize, self.gbRecShowActualState)
        GWOpcionesDialog.setTabOrder(self.gbRecShowActualState, self.optRecMostrarColorFondo)
        GWOpcionesDialog.setTabOrder(self.optRecMostrarColorFondo, self.optRecMostrarIcono)
        GWOpcionesDialog.setTabOrder(self.optRecMostrarIcono, self.gbEntShowActualState)
        GWOpcionesDialog.setTabOrder(self.gbEntShowActualState, self.optEntMostrarColorFondo)
        GWOpcionesDialog.setTabOrder(self.optEntMostrarColorFondo, self.optEntMostrarIcono)
        GWOpcionesDialog.setTabOrder(self.optEntMostrarIcono, self.txtFinalNombre)
        GWOpcionesDialog.setTabOrder(self.txtFinalNombre, self.txtFinalLetra)
        GWOpcionesDialog.setTabOrder(self.txtFinalLetra, self.txtFinalColor)
        GWOpcionesDialog.setTabOrder(self.txtFinalColor, self.btnElegirColorFinal)
        GWOpcionesDialog.setTabOrder(self.btnElegirColorFinal, self.sbFinalRecompensa)
        GWOpcionesDialog.setTabOrder(self.sbFinalRecompensa, self.txtExcelenteNombre)
        GWOpcionesDialog.setTabOrder(self.txtExcelenteNombre, self.txtExcelenteLetra)
        GWOpcionesDialog.setTabOrder(self.txtExcelenteLetra, self.txtExcelenteColor)
        GWOpcionesDialog.setTabOrder(self.txtExcelenteColor, self.btnElegirColorExcelente)
        GWOpcionesDialog.setTabOrder(self.btnElegirColorExcelente, self.sbExcelenteRecompensa)
        GWOpcionesDialog.setTabOrder(self.sbExcelenteRecompensa, self.txtInicialNombre)
        GWOpcionesDialog.setTabOrder(self.txtInicialNombre, self.txtInicialLetra)
        GWOpcionesDialog.setTabOrder(self.txtInicialLetra, self.txtInicialColor)
        GWOpcionesDialog.setTabOrder(self.txtInicialColor, self.btnElegirColorInicial)
        GWOpcionesDialog.setTabOrder(self.btnElegirColorInicial, self.txtBuenoNombre)
        GWOpcionesDialog.setTabOrder(self.txtBuenoNombre, self.txtBuenoLetra)
        GWOpcionesDialog.setTabOrder(self.txtBuenoLetra, self.txtBuenoColor)
        GWOpcionesDialog.setTabOrder(self.txtBuenoColor, self.btnElegirColorBueno)
        GWOpcionesDialog.setTabOrder(self.btnElegirColorBueno, self.sbBuenoRecompensa)
        GWOpcionesDialog.setTabOrder(self.sbBuenoRecompensa, self.txtMaloNombre)
        GWOpcionesDialog.setTabOrder(self.txtMaloNombre, self.txtMaloLetra)
        GWOpcionesDialog.setTabOrder(self.txtMaloLetra, self.txtMaloColor)
        GWOpcionesDialog.setTabOrder(self.txtMaloColor, self.btnElegirColorMalo)
        GWOpcionesDialog.setTabOrder(self.btnElegirColorMalo, self.sbMaloRecompensa)
        GWOpcionesDialog.setTabOrder(self.sbMaloRecompensa, self.txtAgenteNombre)
        GWOpcionesDialog.setTabOrder(self.txtAgenteNombre, self.txtAgenteLetra)
        GWOpcionesDialog.setTabOrder(self.txtAgenteLetra, self.txtAgenteColor)
        GWOpcionesDialog.setTabOrder(self.txtAgenteColor, self.btnElegirColorAgente)
        GWOpcionesDialog.setTabOrder(self.btnElegirColorAgente, self.txtNeutroNombre)
        GWOpcionesDialog.setTabOrder(self.txtNeutroNombre, self.txtNeutroLetra)
        GWOpcionesDialog.setTabOrder(self.txtNeutroLetra, self.txtNeutroColor)
        GWOpcionesDialog.setTabOrder(self.txtNeutroColor, self.btnElegirColorNeutro)
        GWOpcionesDialog.setTabOrder(self.btnElegirColorNeutro, self.sbNeutroRecompensa)
        GWOpcionesDialog.setTabOrder(self.sbNeutroRecompensa, self.txtParedNombre)
        GWOpcionesDialog.setTabOrder(self.txtParedNombre, self.txtParedLetra)
        GWOpcionesDialog.setTabOrder(self.txtParedLetra, self.txtParedColor)
        GWOpcionesDialog.setTabOrder(self.txtParedColor, self.btnElegirColorPared)
        GWOpcionesDialog.setTabOrder(self.btnElegirColorPared, self.btnAceptar)

    def retranslateUi(self, GWOpcionesDialog):
        GWOpcionesDialog.setWindowTitle(_translate("GWOpcionesDialog", "Configurar Grid World", None))
        self.gbEstados.setTitle(_translate("GWOpcionesDialog", "Estados", None))
        self.gbEstadoBueno.setTitle(_translate("GWOpcionesDialog", "Bueno", None))
        self.label_21.setText(_translate("GWOpcionesDialog", "Nombre:", None))
        self.label_22.setText(_translate("GWOpcionesDialog", "Letra:", None))
        self.label_23.setText(_translate("GWOpcionesDialog", "Color:", None))
        self.txtBuenoColor.setInputMask(_translate("GWOpcionesDialog", "\\#HHHHHH; ", None))
        self.btnElegirColorBueno.setToolTip(_translate("GWOpcionesDialog", "Seleccionar color de estado", None))
        self.btnElegirColorBueno.setText(_translate("GWOpcionesDialog", "...", None))
        self.label_24.setText(_translate("GWOpcionesDialog", "Recompensa:", None))
        self.gbEstadoNeutro.setTitle(_translate("GWOpcionesDialog", "Neutro", None))
        self.label_36.setText(_translate("GWOpcionesDialog", "Nombre:", None))
        self.label_37.setText(_translate("GWOpcionesDialog", "Letra:", None))
        self.label_38.setText(_translate("GWOpcionesDialog", "Color:", None))
        self.txtNeutroColor.setInputMask(_translate("GWOpcionesDialog", "\\#HHHHHH; ", None))
        self.btnElegirColorNeutro.setToolTip(_translate("GWOpcionesDialog", "Seleccionar color de estado", None))
        self.btnElegirColorNeutro.setText(_translate("GWOpcionesDialog", "...", None))
        self.label_39.setText(_translate("GWOpcionesDialog", "Recompensa:", None))
        self.gbEstadoPared.setTitle(_translate("GWOpcionesDialog", "Pared", None))
        self.label_40.setText(_translate("GWOpcionesDialog", "Nombre:", None))
        self.label_41.setText(_translate("GWOpcionesDialog", "Letra:", None))
        self.label_42.setText(_translate("GWOpcionesDialog", "Color:", None))
        self.txtParedColor.setInputMask(_translate("GWOpcionesDialog", "\\#HHHHHH; ", None))
        self.btnElegirColorPared.setToolTip(_translate("GWOpcionesDialog", "Seleccionar color de estado", None))
        self.btnElegirColorPared.setText(_translate("GWOpcionesDialog", "...", None))
        self.gbEstadoExcelente.setTitle(_translate("GWOpcionesDialog", "Excelente", None))
        self.label_16.setText(_translate("GWOpcionesDialog", "Nombre:", None))
        self.label_17.setText(_translate("GWOpcionesDialog", "Letra:", None))
        self.label_18.setText(_translate("GWOpcionesDialog", "Color:", None))
        self.txtExcelenteColor.setInputMask(_translate("GWOpcionesDialog", "\\#HHHHHH; ", None))
        self.btnElegirColorExcelente.setToolTip(_translate("GWOpcionesDialog", "Seleccionar color de estado", None))
        self.btnElegirColorExcelente.setText(_translate("GWOpcionesDialog", "...", None))
        self.label_20.setText(_translate("GWOpcionesDialog", "Recompensa:", None))
        self.gbEstadoFinal.setTitle(_translate("GWOpcionesDialog", "Final", None))
        self.label_13.setText(_translate("GWOpcionesDialog", "Nombre:", None))
        self.label_14.setText(_translate("GWOpcionesDialog", "Letra:", None))
        self.label_15.setText(_translate("GWOpcionesDialog", "Color:", None))
        self.txtFinalColor.setInputMask(_translate("GWOpcionesDialog", "\\#HHHHHH; ", None))
        self.btnElegirColorFinal.setToolTip(_translate("GWOpcionesDialog", "Seleccionar color de estado", None))
        self.btnElegirColorFinal.setText(_translate("GWOpcionesDialog", "...", None))
        self.label_19.setText(_translate("GWOpcionesDialog", "Recompensa:", None))
        self.gbEstadoMalo.setTitle(_translate("GWOpcionesDialog", "Malo", None))
        self.label_29.setText(_translate("GWOpcionesDialog", "Nombre:", None))
        self.label_30.setText(_translate("GWOpcionesDialog", "Letra:", None))
        self.label_31.setText(_translate("GWOpcionesDialog", "Color:", None))
        self.txtMaloColor.setInputMask(_translate("GWOpcionesDialog", "\\#HHHHHH; ", None))
        self.btnElegirColorMalo.setToolTip(_translate("GWOpcionesDialog", "Seleccionar color de estado", None))
        self.btnElegirColorMalo.setText(_translate("GWOpcionesDialog", "...", None))
        self.label_32.setText(_translate("GWOpcionesDialog", "Recompensa:", None))
        self.gbEstadoInicial.setTitle(_translate("GWOpcionesDialog", "Inicial", None))
        self.label_2.setText(_translate("GWOpcionesDialog", "Nombre:", None))
        self.label_8.setText(_translate("GWOpcionesDialog", "Letra:", None))
        self.label_9.setText(_translate("GWOpcionesDialog", "Color:", None))
        self.txtInicialColor.setInputMask(_translate("GWOpcionesDialog", "\\#HHHHHH; ", None))
        self.btnElegirColorInicial.setToolTip(_translate("GWOpcionesDialog", "Seleccionar color de estado", None))
        self.btnElegirColorInicial.setText(_translate("GWOpcionesDialog", "...", None))
        self.gbEstadoAgente.setTitle(_translate("GWOpcionesDialog", "Agente", None))
        self.label_33.setText(_translate("GWOpcionesDialog", "Nombre:", None))
        self.label_34.setText(_translate("GWOpcionesDialog", "Letra:", None))
        self.label_35.setText(_translate("GWOpcionesDialog", "Color:", None))
        self.txtAgenteColor.setInputMask(_translate("GWOpcionesDialog", "\\#HHHHHH; ", None))
        self.btnElegirColorAgente.setToolTip(_translate("GWOpcionesDialog", "Seleccionar color de estado", None))
        self.btnElegirColorAgente.setText(_translate("GWOpcionesDialog", "...", None))
        self.gbFormato.setTitle(_translate("GWOpcionesDialog", "Formato", None))
        self.label.setText(_translate("GWOpcionesDialog", "Tamaño:", None))
        self.gbRecorrido.setTitle(_translate("GWOpcionesDialog", "Recorrido", None))
        self.gbRecShowActualState.setTitle(_translate("GWOpcionesDialog", "Mostrar estado actual", None))
        self.optRecMostrarColorFondo.setText(_translate("GWOpcionesDialog", "Mostrar color de agente", None))
        self.optRecMostrarIcono.setText(_translate("GWOpcionesDialog", "Mostrar ícono de agente", None))
        self.btnAceptar.setText(_translate("GWOpcionesDialog", "&Aceptar", None))
        self.gbEntrenamiento.setTitle(_translate("GWOpcionesDialog", "Entrenamiento", None))
        self.gbEntShowActualState.setTitle(_translate("GWOpcionesDialog", "Mostrar estado actual", None))
        self.optEntMostrarColorFondo.setText(_translate("GWOpcionesDialog", "Mostrar color de agente", None))
        self.optEntMostrarIcono.setText(_translate("GWOpcionesDialog", "Mostrar ícono de agente", None))

import recursos_rc
