# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Sebastian\Mis documentos\Programacion\Proyectos\IA2013TPIRL\gui\qt\IA2013TPIRLGUI\gwopcionesdialog.ui'
#
# Created: Sun May 19 16:06:40 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GWOpcionesDialog(object):
    def setupUi(self, GWOpcionesDialog):
        GWOpcionesDialog.setObjectName(_fromUtf8("GWOpcionesDialog"))
        GWOpcionesDialog.resize(576, 318)
        GWOpcionesDialog.setMinimumSize(QtCore.QSize(576, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/Configurar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GWOpcionesDialog.setWindowIcon(icon)
        GWOpcionesDialog.setModal(True)
        self.gridLayout_9 = QtGui.QGridLayout(GWOpcionesDialog)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.pushButton = QtGui.QPushButton(GWOpcionesDialog)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setDefault(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_8.addWidget(self.pushButton, 5, 2, 1, 1)
        self.gbRecompensas = QtGui.QGroupBox(GWOpcionesDialog)
        self.gbRecompensas.setMinimumSize(QtCore.QSize(200, 0))
        self.gbRecompensas.setObjectName(_fromUtf8("gbRecompensas"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gbRecompensas)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.gbRecompensas)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(70, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.sbRecomFinal = QtGui.QSpinBox(self.gbRecompensas)
        self.sbRecomFinal.setEnabled(False)
        self.sbRecomFinal.setMinimum(-1000)
        self.sbRecomFinal.setMaximum(1000)
        self.sbRecomFinal.setObjectName(_fromUtf8("sbRecomFinal"))
        self.horizontalLayout_3.addWidget(self.sbRecomFinal)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.gbRecompensas)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(70, 0))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.sbRecomMalo = QtGui.QSpinBox(self.gbRecompensas)
        self.sbRecomMalo.setMinimum(-1000)
        self.sbRecomMalo.setMaximum(1000)
        self.sbRecomMalo.setObjectName(_fromUtf8("sbRecomMalo"))
        self.horizontalLayout_6.addWidget(self.sbRecomMalo)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_7 = QtGui.QLabel(self.gbRecompensas)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(70, 0))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.cbRecomPared = QtGui.QComboBox(self.gbRecompensas)
        self.cbRecomPared.setObjectName(_fromUtf8("cbRecomPared"))
        self.gridLayout_2.addWidget(self.cbRecomPared, 0, 1, 1, 1)
        self.sbRecomPared = QtGui.QSpinBox(self.gbRecompensas)
        self.sbRecomPared.setMinimum(-1000)
        self.sbRecomPared.setMaximum(1000)
        self.sbRecomPared.setObjectName(_fromUtf8("sbRecomPared"))
        self.gridLayout_2.addWidget(self.sbRecomPared, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.gbRecompensas)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(70, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.sbRecomBueno = QtGui.QSpinBox(self.gbRecompensas)
        self.sbRecomBueno.setMinimum(-1000)
        self.sbRecomBueno.setMaximum(1000)
        self.sbRecomBueno.setObjectName(_fromUtf8("sbRecomBueno"))
        self.horizontalLayout_5.addWidget(self.sbRecomBueno)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.gbRecompensas)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(70, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.sbRecomExcelente = QtGui.QSpinBox(self.gbRecompensas)
        self.sbRecomExcelente.setMinimum(-1000)
        self.sbRecomExcelente.setMaximum(1000)
        self.sbRecomExcelente.setObjectName(_fromUtf8("sbRecomExcelente"))
        self.horizontalLayout_4.addWidget(self.sbRecomExcelente)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.gbRecompensas, 1, 0, 2, 1)
        self.gbFormato = QtGui.QGroupBox(GWOpcionesDialog)
        self.gbFormato.setObjectName(_fromUtf8("gbFormato"))
        self.gridLayout = QtGui.QGridLayout(self.gbFormato)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.gbFormato)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.sbGWEstadoSize = QtGui.QSpinBox(self.gbFormato)
        self.sbGWEstadoSize.setMinimum(20)
        self.sbGWEstadoSize.setMaximum(100)
        self.sbGWEstadoSize.setProperty("value", 40)
        self.sbGWEstadoSize.setObjectName(_fromUtf8("sbGWEstadoSize"))
        self.horizontalLayout.addWidget(self.sbGWEstadoSize)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.gbFormato, 0, 0, 1, 1)
        self.gbRecorrido = QtGui.QGroupBox(GWOpcionesDialog)
        self.gbRecorrido.setMinimumSize(QtCore.QSize(313, 0))
        self.gbRecorrido.setObjectName(_fromUtf8("gbRecorrido"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gbRecorrido)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gbRecShowActualState = QtGui.QGroupBox(self.gbRecorrido)
        self.gbRecShowActualState.setFlat(True)
        self.gbRecShowActualState.setCheckable(True)
        self.gbRecShowActualState.setObjectName(_fromUtf8("gbRecShowActualState"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gbRecShowActualState)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.optRecMostrarColorFondo = QtGui.QRadioButton(self.gbRecShowActualState)
        self.optRecMostrarColorFondo.setMinimumSize(QtCore.QSize(140, 0))
        self.optRecMostrarColorFondo.setChecked(True)
        self.optRecMostrarColorFondo.setObjectName(_fromUtf8("optRecMostrarColorFondo"))
        self.horizontalLayout_7.addWidget(self.optRecMostrarColorFondo)
        self.lblRecActStateBG = QtGui.QLabel(self.gbRecShowActualState)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRecActStateBG.sizePolicy().hasHeightForWidth())
        self.lblRecActStateBG.setSizePolicy(sizePolicy)
        self.lblRecActStateBG.setMinimumSize(QtCore.QSize(55, 20))
        self.lblRecActStateBG.setMaximumSize(QtCore.QSize(20, 20))
        self.lblRecActStateBG.setFrameShape(QtGui.QFrame.Box)
        self.lblRecActStateBG.setText(_fromUtf8(""))
        self.lblRecActStateBG.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lblRecActStateBG.setObjectName(_fromUtf8("lblRecActStateBG"))
        self.horizontalLayout_7.addWidget(self.lblRecActStateBG)
        self.btnRecSelectActStateBG = QtGui.QToolButton(self.gbRecShowActualState)
        self.btnRecSelectActStateBG.setObjectName(_fromUtf8("btnRecSelectActStateBG"))
        self.horizontalLayout_7.addWidget(self.btnRecSelectActStateBG)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.optRecMostrarIcono = QtGui.QRadioButton(self.gbRecShowActualState)
        self.optRecMostrarIcono.setObjectName(_fromUtf8("optRecMostrarIcono"))
        self.verticalLayout_2.addWidget(self.optRecMostrarIcono)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.gbRecShowActualState, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.gbRecorrido, 2, 1, 1, 2)
        self.gbEntrenamiento = QtGui.QGroupBox(GWOpcionesDialog)
        self.gbEntrenamiento.setMinimumSize(QtCore.QSize(313, 0))
        self.gbEntrenamiento.setObjectName(_fromUtf8("gbEntrenamiento"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gbEntrenamiento)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gbEntShowActualState = QtGui.QGroupBox(self.gbEntrenamiento)
        self.gbEntShowActualState.setFlat(True)
        self.gbEntShowActualState.setCheckable(True)
        self.gbEntShowActualState.setObjectName(_fromUtf8("gbEntShowActualState"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gbEntShowActualState)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.optEntMostrarColorFondo = QtGui.QRadioButton(self.gbEntShowActualState)
        self.optEntMostrarColorFondo.setMinimumSize(QtCore.QSize(140, 0))
        self.optEntMostrarColorFondo.setChecked(True)
        self.optEntMostrarColorFondo.setObjectName(_fromUtf8("optEntMostrarColorFondo"))
        self.horizontalLayout_2.addWidget(self.optEntMostrarColorFondo)
        self.lblEntActStateBG = QtGui.QLabel(self.gbEntShowActualState)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEntActStateBG.sizePolicy().hasHeightForWidth())
        self.lblEntActStateBG.setSizePolicy(sizePolicy)
        self.lblEntActStateBG.setMinimumSize(QtCore.QSize(55, 20))
        self.lblEntActStateBG.setMaximumSize(QtCore.QSize(20, 20))
        self.lblEntActStateBG.setFrameShape(QtGui.QFrame.Box)
        self.lblEntActStateBG.setText(_fromUtf8(""))
        self.lblEntActStateBG.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lblEntActStateBG.setObjectName(_fromUtf8("lblEntActStateBG"))
        self.horizontalLayout_2.addWidget(self.lblEntActStateBG)
        self.btnEntSelectActStateBG = QtGui.QToolButton(self.gbEntShowActualState)
        self.btnEntSelectActStateBG.setObjectName(_fromUtf8("btnEntSelectActStateBG"))
        self.horizontalLayout_2.addWidget(self.btnEntSelectActStateBG)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.optEntMostrarIcono = QtGui.QRadioButton(self.gbEntShowActualState)
        self.optEntMostrarIcono.setObjectName(_fromUtf8("optEntMostrarIcono"))
        self.verticalLayout.addWidget(self.optEntMostrarIcono)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.gbEntShowActualState, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.gbEntrenamiento, 0, 1, 2, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 3, 2, 1, 1)
        self.line = QtGui.QFrame(GWOpcionesDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_8.addWidget(self.line, 4, 0, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 5, 0, 1, 2)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.label_3.setBuddy(self.sbRecomFinal)
        self.label_6.setBuddy(self.sbRecomMalo)
        self.label_7.setBuddy(self.cbRecomPared)
        self.label_5.setBuddy(self.sbRecomBueno)
        self.label_4.setBuddy(self.sbRecomExcelente)
        self.label.setBuddy(self.sbGWEstadoSize)
        self.lblRecActStateBG.setBuddy(self.btnRecSelectActStateBG)
        self.lblEntActStateBG.setBuddy(self.btnEntSelectActStateBG)

        self.retranslateUi(GWOpcionesDialog)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), GWOpcionesDialog.accept)
        QtCore.QObject.connect(self.optEntMostrarColorFondo, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.btnEntSelectActStateBG.setEnabled)
        QtCore.QObject.connect(self.optRecMostrarColorFondo, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.btnRecSelectActStateBG.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(GWOpcionesDialog)
        GWOpcionesDialog.setTabOrder(self.sbGWEstadoSize, self.sbRecomFinal)
        GWOpcionesDialog.setTabOrder(self.sbRecomFinal, self.sbRecomExcelente)
        GWOpcionesDialog.setTabOrder(self.sbRecomExcelente, self.sbRecomBueno)
        GWOpcionesDialog.setTabOrder(self.sbRecomBueno, self.sbRecomMalo)
        GWOpcionesDialog.setTabOrder(self.sbRecomMalo, self.cbRecomPared)
        GWOpcionesDialog.setTabOrder(self.cbRecomPared, self.sbRecomPared)
        GWOpcionesDialog.setTabOrder(self.sbRecomPared, self.gbEntShowActualState)
        GWOpcionesDialog.setTabOrder(self.gbEntShowActualState, self.optEntMostrarColorFondo)
        GWOpcionesDialog.setTabOrder(self.optEntMostrarColorFondo, self.btnEntSelectActStateBG)
        GWOpcionesDialog.setTabOrder(self.btnEntSelectActStateBG, self.optEntMostrarIcono)
        GWOpcionesDialog.setTabOrder(self.optEntMostrarIcono, self.gbRecShowActualState)
        GWOpcionesDialog.setTabOrder(self.gbRecShowActualState, self.optRecMostrarColorFondo)
        GWOpcionesDialog.setTabOrder(self.optRecMostrarColorFondo, self.btnRecSelectActStateBG)
        GWOpcionesDialog.setTabOrder(self.btnRecSelectActStateBG, self.optRecMostrarIcono)
        GWOpcionesDialog.setTabOrder(self.optRecMostrarIcono, self.pushButton)

    def retranslateUi(self, GWOpcionesDialog):
        GWOpcionesDialog.setWindowTitle(_translate("GWOpcionesDialog", "Configurar Grid World", None))
        self.pushButton.setText(_translate("GWOpcionesDialog", "&Aceptar", None))
        self.gbRecompensas.setTitle(_translate("GWOpcionesDialog", "Recompensas", None))
        self.label_3.setText(_translate("GWOpcionesDialog", "Final:", None))
        self.label_6.setText(_translate("GWOpcionesDialog", "Malo:", None))
        self.label_7.setText(_translate("GWOpcionesDialog", "Pared:", None))
        self.label_5.setText(_translate("GWOpcionesDialog", "Bueno:", None))
        self.label_4.setText(_translate("GWOpcionesDialog", "Excelente:", None))
        self.gbFormato.setTitle(_translate("GWOpcionesDialog", "Formato", None))
        self.label.setText(_translate("GWOpcionesDialog", "Tamaño:", None))
        self.gbRecorrido.setTitle(_translate("GWOpcionesDialog", "Recorrido", None))
        self.gbRecShowActualState.setTitle(_translate("GWOpcionesDialog", "Mostrar estado actual", None))
        self.optRecMostrarColorFondo.setText(_translate("GWOpcionesDialog", "Mostrar color de fondo", None))
        self.btnRecSelectActStateBG.setText(_translate("GWOpcionesDialog", "Seleccionar color...", None))
        self.optRecMostrarIcono.setText(_translate("GWOpcionesDialog", "Mostrar ícono de agente", None))
        self.gbEntrenamiento.setTitle(_translate("GWOpcionesDialog", "Entrenamiento", None))
        self.gbEntShowActualState.setTitle(_translate("GWOpcionesDialog", "Mostrar estado actual", None))
        self.optEntMostrarColorFondo.setText(_translate("GWOpcionesDialog", "Mostrar color de fondo", None))
        self.btnEntSelectActStateBG.setText(_translate("GWOpcionesDialog", "Seleccionar color...", None))
        self.optEntMostrarIcono.setText(_translate("GWOpcionesDialog", "Mostrar ícono de agente", None))

import recursos_rc
