# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Sebastian\Mis documentos\Programacion\Proyectos\IA2013TPIRL\gui\qt\IA2013TPIRLGUI\mainwindow.ui'
#
# Created: Tue Jul 09 15:27:46 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(907, 817)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/logos/LogoUTN_2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_14 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.tblGridWorld = QtGui.QTableWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblGridWorld.sizePolicy().hasHeightForWidth())
        self.tblGridWorld.setSizePolicy(sizePolicy)
        self.tblGridWorld.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblGridWorld.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblGridWorld.setAutoScroll(False)
        self.tblGridWorld.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.tblGridWorld.setTabKeyNavigation(False)
        self.tblGridWorld.setProperty("showDropIndicator", False)
        self.tblGridWorld.setDragDropOverwriteMode(False)
        self.tblGridWorld.setAlternatingRowColors(False)
        self.tblGridWorld.setCornerButtonEnabled(False)
        self.tblGridWorld.setObjectName(_fromUtf8("tblGridWorld"))
        self.tblGridWorld.setColumnCount(0)
        self.tblGridWorld.setRowCount(0)
        self.gridLayout_14.addWidget(self.tblGridWorld, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.dwGridWorld = QtGui.QDockWidget(MainWindow)
        self.dwGridWorld.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dwGridWorld.setObjectName(_fromUtf8("dwGridWorld"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.gridLayout_32 = QtGui.QGridLayout(self.dockWidgetContents_5)
        self.gridLayout_32.setContentsMargins(4, 2, 4, 4)
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.gbGridWorld = QtGui.QGroupBox(self.dockWidgetContents_5)
        self.gbGridWorld.setObjectName(_fromUtf8("gbGridWorld"))
        self.gridLayout_29 = QtGui.QGridLayout(self.gbGridWorld)
        self.gridLayout_29.setContentsMargins(-1, -1, -1, 6)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.groupBox_8 = QtGui.QGroupBox(self.gbGridWorld)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_30 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_30.setContentsMargins(-1, 4, -1, 2)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.gridLayout_31 = QtGui.QGridLayout()
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.btnInicializarGW = QtGui.QPushButton(self.groupBox_8)
        self.btnInicializarGW.setMaximumSize(QtCore.QSize(90, 22))
        self.btnInicializarGW.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.btnInicializarGW.setObjectName(_fromUtf8("btnInicializarGW"))
        self.gridLayout_31.addWidget(self.btnInicializarGW, 0, 0, 1, 1)
        self.btnGWGenerarEstados = QtGui.QPushButton(self.groupBox_8)
        self.btnGWGenerarEstados.setMaximumSize(QtCore.QSize(16777215, 22))
        self.btnGWGenerarEstados.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.btnGWGenerarEstados.setObjectName(_fromUtf8("btnGWGenerarEstados"))
        self.gridLayout_31.addWidget(self.btnGWGenerarEstados, 0, 1, 1, 1)
        self.btnGWOpciones = QtGui.QToolButton(self.groupBox_8)
        self.btnGWOpciones.setMinimumSize(QtCore.QSize(25, 0))
        self.btnGWOpciones.setMaximumSize(QtCore.QSize(16777215, 22))
        self.btnGWOpciones.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.btnGWOpciones.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/Configurar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGWOpciones.setIcon(icon1)
        self.btnGWOpciones.setObjectName(_fromUtf8("btnGWOpciones"))
        self.gridLayout_31.addWidget(self.btnGWOpciones, 0, 3, 1, 1)
        self.btnGenEstRndRapida = QtGui.QPushButton(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGenEstRndRapida.sizePolicy().hasHeightForWidth())
        self.btnGenEstRndRapida.setSizePolicy(sizePolicy)
        self.btnGenEstRndRapida.setMinimumSize(QtCore.QSize(25, 0))
        self.btnGenEstRndRapida.setMaximumSize(QtCore.QSize(16777215, 22))
        self.btnGenEstRndRapida.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/Random.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGenEstRndRapida.setIcon(icon2)
        self.btnGenEstRndRapida.setObjectName(_fromUtf8("btnGenEstRndRapida"))
        self.gridLayout_31.addWidget(self.btnGenEstRndRapida, 0, 2, 1, 1)
        self.gridLayout_30.addLayout(self.gridLayout_31, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_18 = QtGui.QLabel(self.gbGridWorld)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_9.addWidget(self.label_18)
        self.cbGWDimension = QtGui.QComboBox(self.gbGridWorld)
        self.cbGWDimension.setObjectName(_fromUtf8("cbGWDimension"))
        self.horizontalLayout_9.addWidget(self.cbGWDimension)
        self.gridLayout_29.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.gridLayout_32.addWidget(self.gbGridWorld, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_32.addItem(spacerItem, 1, 0, 1, 1)
        self.dwGridWorld.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dwGridWorld)
        self.dwQLearning = QtGui.QDockWidget(MainWindow)
        self.dwQLearning.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.dwQLearning.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dwQLearning.setObjectName(_fromUtf8("dwQLearning"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_5 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_5.setContentsMargins(-1, 4, -1, 4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.stackedWidget = QtGui.QStackedWidget(self.dockWidgetContents)
        self.stackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pgQLOpciones = QtGui.QWidget()
        self.pgQLOpciones.setObjectName(_fromUtf8("pgQLOpciones"))
        self.gridLayout_33 = QtGui.QGridLayout(self.pgQLOpciones)
        self.gridLayout_33.setObjectName(_fromUtf8("gridLayout_33"))
        self.gbQLearning = QtGui.QGroupBox(self.pgQLOpciones)
        self.gbQLearning.setObjectName(_fromUtf8("gbQLearning"))
        self.gridLayout_17 = QtGui.QGridLayout(self.gbQLearning)
        self.gridLayout_17.setContentsMargins(6, -1, -1, -1)
        self.gridLayout_17.setVerticalSpacing(4)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.groupBox_6 = QtGui.QGroupBox(self.gbQLearning)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_12.setContentsMargins(4, -1, 2, 5)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gbQLMatrizQ = QtGui.QGroupBox(self.groupBox_6)
        self.gbQLMatrizQ.setAlignment(QtCore.Qt.AlignCenter)
        self.gbQLMatrizQ.setFlat(True)
        self.gbQLMatrizQ.setObjectName(_fromUtf8("gbQLMatrizQ"))
        self.gridLayout_24 = QtGui.QGridLayout(self.gbQLMatrizQ)
        self.gridLayout_24.setContentsMargins(2, 2, 1, 1)
        self.gridLayout_24.setVerticalSpacing(4)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.gridLayout_23 = QtGui.QGridLayout()
        self.gridLayout_23.setVerticalSpacing(4)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem1, 2, 0, 1, 1)
        self.lblMQFormula = QtGui.QLabel(self.gbQLMatrizQ)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMQFormula.sizePolicy().hasHeightForWidth())
        self.lblMQFormula.setSizePolicy(sizePolicy)
        self.lblMQFormula.setMinimumSize(QtCore.QSize(158, 0))
        self.lblMQFormula.setObjectName(_fromUtf8("lblMQFormula"))
        self.gridLayout_23.addWidget(self.lblMQFormula, 2, 1, 1, 1)
        self.sbValOptimoIncremento = QtGui.QSpinBox(self.gbQLMatrizQ)
        self.sbValOptimoIncremento.setMinimumSize(QtCore.QSize(60, 0))
        self.sbValOptimoIncremento.setMinimum(1)
        self.sbValOptimoIncremento.setMaximum(100000)
        self.sbValOptimoIncremento.setObjectName(_fromUtf8("sbValOptimoIncremento"))
        self.gridLayout_23.addWidget(self.sbValOptimoIncremento, 2, 2, 1, 1)
        self.optMQInitValOptimistas = QtGui.QRadioButton(self.gbQLMatrizQ)
        self.optMQInitValOptimistas.setObjectName(_fromUtf8("optMQInitValOptimistas"))
        self.gridLayout_23.addWidget(self.optMQInitValOptimistas, 1, 0, 1, 3)
        self.optMQInitEnCero = QtGui.QRadioButton(self.gbQLMatrizQ)
        self.optMQInitEnCero.setObjectName(_fromUtf8("optMQInitEnCero"))
        self.gridLayout_23.addWidget(self.optMQInitEnCero, 0, 0, 1, 3)
        self.gridLayout_24.addLayout(self.gridLayout_23, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.gbQLMatrizQ, 2, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 4, 2, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(98, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(12, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.sbCantEpisodiosDec = QtGui.QSpinBox(self.groupBox_6)
        self.sbCantEpisodiosDec.setMinimum(1)
        self.sbCantEpisodiosDec.setMaximum(1000000000)
        self.sbCantEpisodiosDec.setObjectName(_fromUtf8("sbCantEpisodiosDec"))
        self.gridLayout_2.addWidget(self.sbCantEpisodiosDec, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(98, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sbDecrementoVal = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.sbDecrementoVal.setMinimumSize(QtCore.QSize(50, 0))
        self.sbDecrementoVal.setDecimals(2)
        self.sbDecrementoVal.setMinimum(0.01)
        self.sbDecrementoVal.setMaximum(0.99)
        self.sbDecrementoVal.setSingleStep(0.01)
        self.sbDecrementoVal.setProperty("value", 0.01)
        self.sbDecrementoVal.setObjectName(_fromUtf8("sbDecrementoVal"))
        self.horizontalLayout_3.addWidget(self.sbDecrementoVal)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 2, 1, 1)
        self.chkDecrementarParam = QtGui.QCheckBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chkDecrementarParam.sizePolicy().hasHeightForWidth())
        self.chkDecrementarParam.setSizePolicy(sizePolicy)
        self.chkDecrementarParam.setObjectName(_fromUtf8("chkDecrementarParam"))
        self.gridLayout_2.addWidget(self.chkDecrementarParam, 0, 0, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(12, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblTau = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTau.sizePolicy().hasHeightForWidth())
        self.lblTau.setSizePolicy(sizePolicy)
        self.lblTau.setMinimumSize(QtCore.QSize(116, 0))
        self.lblTau.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lblTau.setObjectName(_fromUtf8("lblTau"))
        self.gridLayout_4.addWidget(self.lblTau, 2, 0, 1, 2)
        self.cbQLTecnicas = QtGui.QComboBox(self.groupBox_6)
        self.cbQLTecnicas.setObjectName(_fromUtf8("cbQLTecnicas"))
        self.gridLayout_4.addWidget(self.cbQLTecnicas, 0, 2, 1, 2)
        self.lblEpsilon = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEpsilon.sizePolicy().hasHeightForWidth())
        self.lblEpsilon.setSizePolicy(sizePolicy)
        self.lblEpsilon.setMinimumSize(QtCore.QSize(116, 0))
        self.lblEpsilon.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lblEpsilon.setObjectName(_fromUtf8("lblEpsilon"))
        self.gridLayout_4.addWidget(self.lblEpsilon, 1, 0, 1, 2)
        self.lblTecnica = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTecnica.sizePolicy().hasHeightForWidth())
        self.lblTecnica.setSizePolicy(sizePolicy)
        self.lblTecnica.setMaximumSize(QtCore.QSize(125, 16777215))
        self.lblTecnica.setObjectName(_fromUtf8("lblTecnica"))
        self.gridLayout_4.addWidget(self.lblTecnica, 0, 0, 1, 2)
        self.sbQLEpsilon = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.sbQLEpsilon.setMinimum(0.01)
        self.sbQLEpsilon.setMaximum(0.99)
        self.sbQLEpsilon.setSingleStep(0.01)
        self.sbQLEpsilon.setProperty("value", 0.1)
        self.sbQLEpsilon.setObjectName(_fromUtf8("sbQLEpsilon"))
        self.gridLayout_4.addWidget(self.sbQLEpsilon, 1, 2, 1, 2)
        self.sbQLTau = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.sbQLTau.setMinimum(1.0)
        self.sbQLTau.setMaximum(1000000000.0)
        self.sbQLTau.setSingleStep(1.0)
        self.sbQLTau.setObjectName(_fromUtf8("sbQLTau"))
        self.gridLayout_4.addWidget(self.sbQLTau, 2, 2, 1, 2)
        self.gridLayout_12.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_6, 2, 0, 1, 2)
        self.gbCondicionParada = QtGui.QGroupBox(self.gbQLearning)
        self.gbCondicionParada.setAlignment(QtCore.Qt.AlignCenter)
        self.gbCondicionParada.setFlat(True)
        self.gbCondicionParada.setObjectName(_fromUtf8("gbCondicionParada"))
        self.gridLayout_10 = QtGui.QGridLayout(self.gbCondicionParada)
        self.gridLayout_10.setContentsMargins(2, 4, 2, 4)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_2 = QtGui.QLabel(self.gbCondicionParada)
        self.label_2.setMinimumSize(QtCore.QSize(110, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.sbCantidadEpisodios = QtGui.QSpinBox(self.gbCondicionParada)
        self.sbCantidadEpisodios.setMinimum(1)
        self.sbCantidadEpisodios.setMaximum(1000000000)
        self.sbCantidadEpisodios.setObjectName(_fromUtf8("sbCantidadEpisodios"))
        self.gridLayout_8.addWidget(self.sbCantidadEpisodios, 0, 1, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setVerticalSpacing(3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lblCantMaxIteraciones = QtGui.QLabel(self.gbCondicionParada)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCantMaxIteraciones.sizePolicy().hasHeightForWidth())
        self.lblCantMaxIteraciones.setSizePolicy(sizePolicy)
        self.lblCantMaxIteraciones.setMinimumSize(QtCore.QSize(102, 0))
        self.lblCantMaxIteraciones.setObjectName(_fromUtf8("lblCantMaxIteraciones"))
        self.gridLayout_7.addWidget(self.lblCantMaxIteraciones, 2, 1, 1, 1)
        self.sbCantMaxIteraciones = QtGui.QSpinBox(self.gbCondicionParada)
        self.sbCantMaxIteraciones.setMinimum(1)
        self.sbCantMaxIteraciones.setMaximum(1000000000)
        self.sbCantMaxIteraciones.setObjectName(_fromUtf8("sbCantMaxIteraciones"))
        self.gridLayout_7.addWidget(self.sbCantMaxIteraciones, 2, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(12, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 2, 0, 1, 1)
        self.chkLimitarCantIteraciones = QtGui.QCheckBox(self.gbCondicionParada)
        self.chkLimitarCantIteraciones.setObjectName(_fromUtf8("chkLimitarCantIteraciones"))
        self.gridLayout_7.addWidget(self.chkLimitarCantIteraciones, 1, 0, 1, 3)
        self.gridLayout_8.addLayout(self.gridLayout_7, 1, 0, 1, 2)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblMatQDiff = QtGui.QLabel(self.gbCondicionParada)
        self.lblMatQDiff.setObjectName(_fromUtf8("lblMatQDiff"))
        self.gridLayout_6.addWidget(self.lblMatQDiff, 1, 1, 1, 1)
        self.lblMatQIntervalo = QtGui.QLabel(self.gbCondicionParada)
        self.lblMatQIntervalo.setObjectName(_fromUtf8("lblMatQIntervalo"))
        self.gridLayout_6.addWidget(self.lblMatQIntervalo, 2, 1, 1, 1)
        self.sbIntervaloDiffCalc = QtGui.QSpinBox(self.gbCondicionParada)
        self.sbIntervaloDiffCalc.setSuffix(_fromUtf8(""))
        self.sbIntervaloDiffCalc.setMinimum(1)
        self.sbIntervaloDiffCalc.setMaximum(10000)
        self.sbIntervaloDiffCalc.setProperty("value", 5)
        self.sbIntervaloDiffCalc.setObjectName(_fromUtf8("sbIntervaloDiffCalc"))
        self.gridLayout_6.addWidget(self.sbIntervaloDiffCalc, 2, 2, 1, 1)
        self.sbMatricesMinDiff = QtGui.QDoubleSpinBox(self.gbCondicionParada)
        self.sbMatricesMinDiff.setDecimals(15)
        self.sbMatricesMinDiff.setMinimum(1e-06)
        self.sbMatricesMinDiff.setMaximum(1000000000.0)
        self.sbMatricesMinDiff.setSingleStep(1e-06)
        self.sbMatricesMinDiff.setProperty("value", 1e-05)
        self.sbMatricesMinDiff.setObjectName(_fromUtf8("sbMatricesMinDiff"))
        self.gridLayout_6.addWidget(self.sbMatricesMinDiff, 1, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(14, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(14, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 2, 0, 1, 1)
        self.chkQLCalcularMatDiff = QtGui.QCheckBox(self.gbCondicionParada)
        self.chkQLCalcularMatDiff.setObjectName(_fromUtf8("chkQLCalcularMatDiff"))
        self.gridLayout_6.addWidget(self.chkQLCalcularMatDiff, 0, 0, 1, 3)
        self.gridLayout_8.addLayout(self.gridLayout_6, 2, 0, 1, 2)
        self.gridLayout_10.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.gbCondicionParada, 1, 0, 1, 2)
        self.lblGamma = QtGui.QLabel(self.gbQLearning)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGamma.sizePolicy().hasHeightForWidth())
        self.lblGamma.setSizePolicy(sizePolicy)
        self.lblGamma.setMinimumSize(QtCore.QSize(122, 0))
        self.lblGamma.setObjectName(_fromUtf8("lblGamma"))
        self.gridLayout_17.addWidget(self.lblGamma, 0, 0, 1, 1)
        self.sbQLGamma = QtGui.QDoubleSpinBox(self.gbQLearning)
        self.sbQLGamma.setMinimum(0.01)
        self.sbQLGamma.setMaximum(0.99)
        self.sbQLGamma.setSingleStep(0.01)
        self.sbQLGamma.setObjectName(_fromUtf8("sbQLGamma"))
        self.gridLayout_17.addWidget(self.sbQLGamma, 0, 1, 1, 1)
        self.gridLayout_33.addWidget(self.gbQLearning, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pgQLOpciones)
        self.pgQLAcciones = QtGui.QWidget()
        self.pgQLAcciones.setObjectName(_fromUtf8("pgQLAcciones"))
        self.gridLayout_34 = QtGui.QGridLayout(self.pgQLAcciones)
        self.gridLayout_34.setObjectName(_fromUtf8("gridLayout_34"))
        self.groupBox_7 = QtGui.QGroupBox(self.pgQLAcciones)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_13.setContentsMargins(-1, 4, -1, -1)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.btnInicializarValoresQL = QtGui.QPushButton(self.groupBox_7)
        self.btnInicializarValoresQL.setMaximumSize(QtCore.QSize(130, 22))
        self.btnInicializarValoresQL.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.btnInicializarValoresQL.setObjectName(_fromUtf8("btnInicializarValoresQL"))
        self.gridLayout_13.addWidget(self.btnInicializarValoresQL, 0, 0, 1, 1)
        self.gridLayout_34.addWidget(self.groupBox_7, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_34.addItem(spacerItem7, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.pgQLAcciones)
        self.gridLayout_5.addWidget(self.stackedWidget, 0, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem8, 1, 0, 1, 1)
        self.dwQLearning.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dwQLearning)
        self.dwEjecucion = QtGui.QDockWidget(MainWindow)
        self.dwEjecucion.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.dwEjecucion.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dwEjecucion.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dwEjecucion.setObjectName(_fromUtf8("dwEjecucion"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.gridLayout_19 = QtGui.QGridLayout(self.dockWidgetContents_4)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem9, 3, 1, 1, 1)
        self.gbMatrizQ = QtGui.QGroupBox(self.dockWidgetContents_4)
        self.gbMatrizQ.setObjectName(_fromUtf8("gbMatrizQ"))
        self.gridLayout_20 = QtGui.QGridLayout(self.gbMatrizQ)
        self.gridLayout_20.setSpacing(3)
        self.gridLayout_20.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.btnMostrarMatrizQ = QtGui.QPushButton(self.gbMatrizQ)
        self.btnMostrarMatrizQ.setMinimumSize(QtCore.QSize(105, 0))
        self.btnMostrarMatrizQ.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.btnMostrarMatrizQ.setObjectName(_fromUtf8("btnMostrarMatrizQ"))
        self.gridLayout_20.addWidget(self.btnMostrarMatrizQ, 0, 0, 1, 1)
        self.btnMatrizQVerHM = QtGui.QPushButton(self.gbMatrizQ)
        self.btnMatrizQVerHM.setObjectName(_fromUtf8("btnMatrizQVerHM"))
        self.gridLayout_20.addWidget(self.btnMatrizQVerHM, 1, 0, 1, 1)
        self.gridLayout_19.addWidget(self.gbMatrizQ, 1, 1, 1, 1)
        self.gbMatrizR = QtGui.QGroupBox(self.dockWidgetContents_4)
        self.gbMatrizR.setObjectName(_fromUtf8("gbMatrizR"))
        self.gridLayout_27 = QtGui.QGridLayout(self.gbMatrizR)
        self.gridLayout_27.setSpacing(3)
        self.gridLayout_27.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.btnMostrarMatrizR = QtGui.QPushButton(self.gbMatrizR)
        self.btnMostrarMatrizR.setMinimumSize(QtCore.QSize(105, 0))
        self.btnMostrarMatrizR.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.btnMostrarMatrizR.setObjectName(_fromUtf8("btnMostrarMatrizR"))
        self.gridLayout_27.addWidget(self.btnMostrarMatrizR, 0, 0, 1, 1)
        self.btnMatrizRVerHM = QtGui.QPushButton(self.gbMatrizR)
        self.btnMatrizRVerHM.setObjectName(_fromUtf8("btnMatrizRVerHM"))
        self.gridLayout_27.addWidget(self.btnMatrizRVerHM, 1, 0, 1, 1)
        self.gridLayout_19.addWidget(self.gbMatrizR, 0, 1, 1, 1)
        self.gbAgente = QtGui.QGroupBox(self.dockWidgetContents_4)
        self.gbAgente.setObjectName(_fromUtf8("gbAgente"))
        self.gridLayout_18 = QtGui.QGridLayout(self.gbAgente)
        self.gridLayout_18.setContentsMargins(-1, 4, -1, 4)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.btnEntrenar = QtGui.QPushButton(self.gbAgente)
        self.btnEntrenar.setMinimumSize(QtCore.QSize(100, 0))
        self.btnEntrenar.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/Aprender.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEntrenar.setIcon(icon3)
        self.btnEntrenar.setObjectName(_fromUtf8("btnEntrenar"))
        self.verticalLayout.addWidget(self.btnEntrenar)
        self.btnRecorrer = QtGui.QPushButton(self.gbAgente)
        self.btnRecorrer.setMinimumSize(QtCore.QSize(100, 24))
        self.btnRecorrer.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/Recorrer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRecorrer.setIcon(icon4)
        self.btnRecorrer.setObjectName(_fromUtf8("btnRecorrer"))
        self.verticalLayout.addWidget(self.btnRecorrer)
        self.btnPausar = QtGui.QPushButton(self.gbAgente)
        self.btnPausar.setMinimumSize(QtCore.QSize(100, 24))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/Pausar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPausar.setIcon(icon5)
        self.btnPausar.setObjectName(_fromUtf8("btnPausar"))
        self.verticalLayout.addWidget(self.btnPausar)
        self.btnTerminarProceso = QtGui.QPushButton(self.gbAgente)
        self.btnTerminarProceso.setMinimumSize(QtCore.QSize(100, 24))
        self.btnTerminarProceso.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/Detener.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTerminarProceso.setIcon(icon6)
        self.btnTerminarProceso.setObjectName(_fromUtf8("btnTerminarProceso"))
        self.verticalLayout.addWidget(self.btnTerminarProceso)
        self.gridLayout_18.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.gbAgente, 0, 0, 3, 1)
        self.dwEjecucion.setWidget(self.dockWidgetContents_4)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dwEjecucion)
        self.dwCaminoOptimo = QtGui.QDockWidget(MainWindow)
        self.dwCaminoOptimo.setMaximumSize(QtCore.QSize(524287, 150))
        self.dwCaminoOptimo.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dwCaminoOptimo.setObjectName(_fromUtf8("dwCaminoOptimo"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_25 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_25.setContentsMargins(-1, 2, -1, 4)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.gbCOAcciones = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.gbCOAcciones.setObjectName(_fromUtf8("gbCOAcciones"))
        self.gridLayout_26 = QtGui.QGridLayout(self.gbCOAcciones)
        self.gridLayout_26.setContentsMargins(-1, 4, -1, 4)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.btnCOShowHide = QtGui.QPushButton(self.gbCOAcciones)
        self.btnCOShowHide.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnCOShowHide.setObjectName(_fromUtf8("btnCOShowHide"))
        self.gridLayout_26.addWidget(self.btnCOShowHide, 0, 0, 1, 1)
        self.btnCOVerDetalles = QtGui.QPushButton(self.gbCOAcciones)
        self.btnCOVerDetalles.setMinimumSize(QtCore.QSize(80, 0))
        self.btnCOVerDetalles.setObjectName(_fromUtf8("btnCOVerDetalles"))
        self.gridLayout_26.addWidget(self.btnCOVerDetalles, 1, 0, 1, 1)
        self.gridLayout_25.addWidget(self.gbCOAcciones, 0, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem10, 2, 0, 1, 1)
        self.gbCOAvance = QtGui.QGroupBox(self.dockWidgetContents_2)
        self.gbCOAvance.setObjectName(_fromUtf8("gbCOAvance"))
        self.gridLayout_11 = QtGui.QGridLayout(self.gbCOAvance)
        self.gridLayout_11.setContentsMargins(5, 4, -1, 4)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.btnCOAtras = QtGui.QPushButton(self.gbCOAvance)
        self.btnCOAtras.setMaximumSize(QtCore.QSize(80, 16777215))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/Atras.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCOAtras.setIcon(icon7)
        self.btnCOAtras.setObjectName(_fromUtf8("btnCOAtras"))
        self.horizontalLayout.addWidget(self.btnCOAtras)
        self.btnCOAdelante = QtGui.QPushButton(self.gbCOAvance)
        self.btnCOAdelante.setMaximumSize(QtCore.QSize(80, 16777215))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/Adelante.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCOAdelante.setIcon(icon8)
        self.btnCOAdelante.setObjectName(_fromUtf8("btnCOAdelante"))
        self.horizontalLayout.addWidget(self.btnCOAdelante)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.gridLayout_11.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.gbCOAvance, 0, 1, 1, 1)
        self.dwCaminoOptimo.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dwCaminoOptimo)
        self.dwMetricas = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwMetricas.sizePolicy().hasHeightForWidth())
        self.dwMetricas.setSizePolicy(sizePolicy)
        self.dwMetricas.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.dwMetricas.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dwMetricas.setObjectName(_fromUtf8("dwMetricas"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout_15 = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gbEntrenamiento = QtGui.QGroupBox(self.dockWidgetContents_3)
        self.gbEntrenamiento.setObjectName(_fromUtf8("gbEntrenamiento"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gbEntrenamiento)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gbEntExecTime = QtGui.QGroupBox(self.gbEntrenamiento)
        self.gbEntExecTime.setAlignment(QtCore.Qt.AlignCenter)
        self.gbEntExecTime.setFlat(True)
        self.gbEntExecTime.setObjectName(_fromUtf8("gbEntExecTime"))
        self.gridLayout_21 = QtGui.QGridLayout(self.gbEntExecTime)
        self.gridLayout_21.setContentsMargins(2, 4, 5, 3)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_13 = QtGui.QLabel(self.gbEntExecTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(86, 0))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_7.addWidget(self.label_13)
        self.lblEntExecTimeEpisodios = QtGui.QLabel(self.gbEntExecTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEntExecTimeEpisodios.sizePolicy().hasHeightForWidth())
        self.lblEntExecTimeEpisodios.setSizePolicy(sizePolicy)
        self.lblEntExecTimeEpisodios.setObjectName(_fromUtf8("lblEntExecTimeEpisodios"))
        self.horizontalLayout_7.addWidget(self.lblEntExecTimeEpisodios)
        self.gridLayout_21.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_11 = QtGui.QLabel(self.gbEntExecTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(86, 0))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.lblEntExecTimeIteraciones = QtGui.QLabel(self.gbEntExecTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEntExecTimeIteraciones.sizePolicy().hasHeightForWidth())
        self.lblEntExecTimeIteraciones.setSizePolicy(sizePolicy)
        self.lblEntExecTimeIteraciones.setObjectName(_fromUtf8("lblEntExecTimeIteraciones"))
        self.horizontalLayout_6.addWidget(self.lblEntExecTimeIteraciones)
        self.gridLayout_21.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_15 = QtGui.QLabel(self.gbEntExecTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(86, 0))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_8.addWidget(self.label_15)
        self.lblEntExecTimeTotal = QtGui.QLabel(self.gbEntExecTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEntExecTimeTotal.sizePolicy().hasHeightForWidth())
        self.lblEntExecTimeTotal.setSizePolicy(sizePolicy)
        self.lblEntExecTimeTotal.setObjectName(_fromUtf8("lblEntExecTimeTotal"))
        self.horizontalLayout_8.addWidget(self.lblEntExecTimeTotal)
        self.gridLayout_21.addLayout(self.horizontalLayout_8, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.gbEntExecTime, 7, 1, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_9 = QtGui.QLabel(self.gbEntrenamiento)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(90, 0))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_5.addWidget(self.label_9)
        self.lblEntNroIteracion = QtGui.QLabel(self.gbEntrenamiento)
        self.lblEntNroIteracion.setObjectName(_fromUtf8("lblEntNroIteracion"))
        self.horizontalLayout_5.addWidget(self.lblEntNroIteracion)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(self.gbEntrenamiento)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(90, 0))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lblEntNroEpisodio = QtGui.QLabel(self.gbEntrenamiento)
        self.lblEntNroEpisodio.setObjectName(_fromUtf8("lblEntNroEpisodio"))
        self.horizontalLayout_4.addWidget(self.lblEntNroEpisodio)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.gbEntrenamiento)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(90, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lblEntEstadoActual = QtGui.QLabel(self.gbEntrenamiento)
        self.lblEntEstadoActual.setObjectName(_fromUtf8("lblEntEstadoActual"))
        self.horizontalLayout_2.addWidget(self.lblEntEstadoActual)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_10 = QtGui.QLabel(self.gbEntrenamiento)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(135, 0))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_12.addWidget(self.label_10)
        self.lblEntValParametro = QtGui.QLabel(self.gbEntrenamiento)
        self.lblEntValParametro.setObjectName(_fromUtf8("lblEntValParametro"))
        self.horizontalLayout_12.addWidget(self.lblEntValParametro)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 3, 1, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem13, 6, 1, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_14 = QtGui.QLabel(self.gbEntrenamiento)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(135, 0))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_15.addWidget(self.label_14)
        self.lblEntDiffMatrices = QtGui.QLabel(self.gbEntrenamiento)
        self.lblEntDiffMatrices.setObjectName(_fromUtf8("lblEntDiffMatrices"))
        self.horizontalLayout_15.addWidget(self.lblEntDiffMatrices)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 4, 1, 2, 1)
        self.gridLayout_15.addWidget(self.gbEntrenamiento, 0, 0, 1, 1)
        self.gbRecorrido = QtGui.QGroupBox(self.dockWidgetContents_3)
        self.gbRecorrido.setObjectName(_fromUtf8("gbRecorrido"))
        self.gridLayout_16 = QtGui.QGridLayout(self.gbRecorrido)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_6 = QtGui.QLabel(self.gbRecorrido)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(90, 0))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_13.addWidget(self.label_6)
        self.lblRecEstadoActual = QtGui.QLabel(self.gbRecorrido)
        self.lblRecEstadoActual.setObjectName(_fromUtf8("lblRecEstadoActual"))
        self.horizontalLayout_13.addWidget(self.lblRecEstadoActual)
        self.gridLayout_16.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_16.addItem(spacerItem14, 1, 0, 1, 1)
        self.gbRecExecTime = QtGui.QGroupBox(self.gbRecorrido)
        self.gbRecExecTime.setAlignment(QtCore.Qt.AlignCenter)
        self.gbRecExecTime.setFlat(True)
        self.gbRecExecTime.setObjectName(_fromUtf8("gbRecExecTime"))
        self.gridLayout_22 = QtGui.QGridLayout(self.gbRecExecTime)
        self.gridLayout_22.setContentsMargins(2, 4, 5, 3)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_16 = QtGui.QLabel(self.gbRecExecTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(86, 0))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_11.addWidget(self.label_16)
        self.lblRecExecTimeTotal = QtGui.QLabel(self.gbRecExecTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRecExecTimeTotal.sizePolicy().hasHeightForWidth())
        self.lblRecExecTimeTotal.setSizePolicy(sizePolicy)
        self.lblRecExecTimeTotal.setObjectName(_fromUtf8("lblRecExecTimeTotal"))
        self.horizontalLayout_11.addWidget(self.lblRecExecTimeTotal)
        self.gridLayout_22.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_17 = QtGui.QLabel(self.gbRecExecTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(86, 0))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_14.addWidget(self.label_17)
        self.lblRecExecTimeRecorrido = QtGui.QLabel(self.gbRecExecTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRecExecTimeRecorrido.sizePolicy().hasHeightForWidth())
        self.lblRecExecTimeRecorrido.setSizePolicy(sizePolicy)
        self.lblRecExecTimeRecorrido.setObjectName(_fromUtf8("lblRecExecTimeRecorrido"))
        self.horizontalLayout_14.addWidget(self.lblRecExecTimeRecorrido)
        self.gridLayout_22.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.gbRecExecTime, 2, 0, 1, 1)
        self.gridLayout_15.addWidget(self.gbRecorrido, 1, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem15, 2, 0, 1, 1)
        self.dwMetricas.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dwMetricas)
        self.dwConfigGeneral = QtGui.QDockWidget(MainWindow)
        self.dwConfigGeneral.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dwConfigGeneral.setObjectName(_fromUtf8("dwConfigGeneral"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents_6)
        self.gridLayout.setContentsMargins(-1, 2, -1, 3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gbGeneral = QtGui.QGroupBox(self.dockWidgetContents_6)
        self.gbGeneral.setObjectName(_fromUtf8("gbGeneral"))
        self.gridLayout_9 = QtGui.QGridLayout(self.gbGeneral)
        self.gridLayout_9.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.btnInicializarTodo = QtGui.QPushButton(self.gbGeneral)
        self.btnInicializarTodo.setMaximumSize(QtCore.QSize(130, 16777215))
        self.btnInicializarTodo.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.btnInicializarTodo.setObjectName(_fromUtf8("btnInicializarTodo"))
        self.gridLayout_9.addWidget(self.btnInicializarTodo, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.gbGeneral, 0, 0, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem16, 1, 0, 1, 1)
        self.dwConfigGeneral.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dwConfigGeneral)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 907, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuArchivo = QtGui.QMenu(self.menuBar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuAyuda = QtGui.QMenu(self.menuBar)
        self.menuAyuda.setObjectName(_fromUtf8("menuAyuda"))
        self.menuOperaciones = QtGui.QMenu(self.menuBar)
        self.menuOperaciones.setObjectName(_fromUtf8("menuOperaciones"))
        self.menuConfiguracion = QtGui.QMenu(self.menuBar)
        self.menuConfiguracion.setObjectName(_fromUtf8("menuConfiguracion"))
        self.menuGridWorld = QtGui.QMenu(self.menuConfiguracion)
        self.menuGridWorld.setObjectName(_fromUtf8("menuGridWorld"))
        self.menuQLearning = QtGui.QMenu(self.menuConfiguracion)
        self.menuQLearning.setObjectName(_fromUtf8("menuQLearning"))
        self.menuHeatmap = QtGui.QMenu(self.menuConfiguracion)
        self.menuHeatmap.setObjectName(_fromUtf8("menuHeatmap"))
        self.menuInterpolacion = QtGui.QMenu(self.menuHeatmap)
        self.menuInterpolacion.setObjectName(_fromUtf8("menuInterpolacion"))
        self.menuAnteBloqueo = QtGui.QMenu(self.menuConfiguracion)
        self.menuAnteBloqueo.setObjectName(_fromUtf8("menuAnteBloqueo"))
        self.menuEstadisticas = QtGui.QMenu(self.menuBar)
        self.menuEstadisticas.setObjectName(_fromUtf8("menuEstadisticas"))
        self.menuPruebas = QtGui.QMenu(self.menuBar)
        self.menuPruebas.setObjectName(_fromUtf8("menuPruebas"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionAppSalir = QtGui.QAction(MainWindow)
        self.actionAppSalir.setObjectName(_fromUtf8("actionAppSalir"))
        self.actionAcercaDe = QtGui.QAction(MainWindow)
        self.actionAcercaDe.setObjectName(_fromUtf8("actionAcercaDe"))
        self.actionAgenteEntrenar = QtGui.QAction(MainWindow)
        self.actionAgenteEntrenar.setIcon(icon3)
        self.actionAgenteEntrenar.setObjectName(_fromUtf8("actionAgenteEntrenar"))
        self.actionAgenteRecorrer = QtGui.QAction(MainWindow)
        self.actionAgenteRecorrer.setIcon(icon4)
        self.actionAgenteRecorrer.setObjectName(_fromUtf8("actionAgenteRecorrer"))
        self.actionAgenteCancelar = QtGui.QAction(MainWindow)
        self.actionAgenteCancelar.setIcon(icon6)
        self.actionAgenteCancelar.setObjectName(_fromUtf8("actionAgenteCancelar"))
        self.actionInicializarTodo = QtGui.QAction(MainWindow)
        self.actionInicializarTodo.setObjectName(_fromUtf8("actionInicializarTodo"))
        self.actionAgentePausar = QtGui.QAction(MainWindow)
        self.actionAgentePausar.setIcon(icon5)
        self.actionAgentePausar.setObjectName(_fromUtf8("actionAgentePausar"))
        self.menuArchivo.addAction(self.actionAppSalir)
        self.menuAyuda.addAction(self.actionAcercaDe)
        self.menuOperaciones.addAction(self.actionAgenteEntrenar)
        self.menuOperaciones.addAction(self.actionAgenteRecorrer)
        self.menuOperaciones.addAction(self.actionAgentePausar)
        self.menuOperaciones.addAction(self.actionAgenteCancelar)
        self.menuHeatmap.addAction(self.menuInterpolacion.menuAction())
        self.menuConfiguracion.addAction(self.menuGridWorld.menuAction())
        self.menuConfiguracion.addAction(self.menuQLearning.menuAction())
        self.menuConfiguracion.addSeparator()
        self.menuConfiguracion.addAction(self.actionInicializarTodo)
        self.menuConfiguracion.addSeparator()
        self.menuConfiguracion.addAction(self.menuHeatmap.menuAction())
        self.menuConfiguracion.addSeparator()
        self.menuConfiguracion.addAction(self.menuAnteBloqueo.menuAction())
        self.menuBar.addAction(self.menuArchivo.menuAction())
        self.menuBar.addAction(self.menuConfiguracion.menuAction())
        self.menuBar.addAction(self.menuOperaciones.menuAction())
        self.menuBar.addAction(self.menuEstadisticas.menuAction())
        self.menuBar.addAction(self.menuPruebas.menuAction())
        self.menuBar.addAction(self.menuAyuda.menuAction())
        self.lblMQFormula.setBuddy(self.sbValOptimoIncremento)
        self.label_3.setBuddy(self.sbCantEpisodiosDec)
        self.label_5.setBuddy(self.sbDecrementoVal)
        self.lblTau.setBuddy(self.sbQLTau)
        self.lblEpsilon.setBuddy(self.sbQLEpsilon)
        self.lblTecnica.setBuddy(self.cbQLTecnicas)
        self.label_2.setBuddy(self.sbCantidadEpisodios)
        self.lblCantMaxIteraciones.setBuddy(self.sbCantMaxIteraciones)
        self.lblMatQDiff.setBuddy(self.sbMatricesMinDiff)
        self.lblMatQIntervalo.setBuddy(self.sbIntervaloDiffCalc)
        self.lblGamma.setBuddy(self.sbQLGamma)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.chkLimitarCantIteraciones, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblCantMaxIteraciones.setEnabled)
        QtCore.QObject.connect(self.chkLimitarCantIteraciones, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sbCantMaxIteraciones.setEnabled)
        QtCore.QObject.connect(self.chkQLCalcularMatDiff, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblMatQDiff.setEnabled)
        QtCore.QObject.connect(self.chkQLCalcularMatDiff, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblMatQIntervalo.setEnabled)
        QtCore.QObject.connect(self.chkQLCalcularMatDiff, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sbMatricesMinDiff.setEnabled)
        QtCore.QObject.connect(self.chkQLCalcularMatDiff, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sbIntervaloDiffCalc.setEnabled)
        QtCore.QObject.connect(self.chkDecrementarParam, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sbCantEpisodiosDec.setEnabled)
        QtCore.QObject.connect(self.chkDecrementarParam, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sbDecrementoVal.setEnabled)
        QtCore.QObject.connect(self.chkDecrementarParam, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_3.setEnabled)
        QtCore.QObject.connect(self.chkDecrementarParam, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_5.setEnabled)
        QtCore.QObject.connect(self.optMQInitValOptimistas, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.lblMQFormula.setEnabled)
        QtCore.QObject.connect(self.optMQInitValOptimistas, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sbValOptimoIncremento.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cbGWDimension, self.btnInicializarGW)
        MainWindow.setTabOrder(self.btnInicializarGW, self.btnGWGenerarEstados)
        MainWindow.setTabOrder(self.btnGWGenerarEstados, self.btnGWOpciones)
        MainWindow.setTabOrder(self.btnGWOpciones, self.sbQLGamma)
        MainWindow.setTabOrder(self.sbQLGamma, self.sbCantidadEpisodios)
        MainWindow.setTabOrder(self.sbCantidadEpisodios, self.chkLimitarCantIteraciones)
        MainWindow.setTabOrder(self.chkLimitarCantIteraciones, self.sbCantMaxIteraciones)
        MainWindow.setTabOrder(self.sbCantMaxIteraciones, self.chkQLCalcularMatDiff)
        MainWindow.setTabOrder(self.chkQLCalcularMatDiff, self.sbMatricesMinDiff)
        MainWindow.setTabOrder(self.sbMatricesMinDiff, self.sbIntervaloDiffCalc)
        MainWindow.setTabOrder(self.sbIntervaloDiffCalc, self.cbQLTecnicas)
        MainWindow.setTabOrder(self.cbQLTecnicas, self.sbQLEpsilon)
        MainWindow.setTabOrder(self.sbQLEpsilon, self.sbQLTau)
        MainWindow.setTabOrder(self.sbQLTau, self.chkDecrementarParam)
        MainWindow.setTabOrder(self.chkDecrementarParam, self.sbCantEpisodiosDec)
        MainWindow.setTabOrder(self.sbCantEpisodiosDec, self.sbDecrementoVal)
        MainWindow.setTabOrder(self.sbDecrementoVal, self.optMQInitEnCero)
        MainWindow.setTabOrder(self.optMQInitEnCero, self.optMQInitValOptimistas)
        MainWindow.setTabOrder(self.optMQInitValOptimistas, self.sbValOptimoIncremento)
        MainWindow.setTabOrder(self.sbValOptimoIncremento, self.btnInicializarTodo)
        MainWindow.setTabOrder(self.btnInicializarTodo, self.tblGridWorld)
        MainWindow.setTabOrder(self.tblGridWorld, self.btnEntrenar)
        MainWindow.setTabOrder(self.btnEntrenar, self.btnRecorrer)
        MainWindow.setTabOrder(self.btnRecorrer, self.btnTerminarProceso)
        MainWindow.setTabOrder(self.btnTerminarProceso, self.btnCOShowHide)
        MainWindow.setTabOrder(self.btnCOShowHide, self.btnInicializarValoresQL)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Grupo Nº 1 - Inteligencia Artificial 2013 - Aprendizaje por Refuerzo", None))
        self.dwGridWorld.setWindowTitle(_translate("MainWindow", "Grid World", None))
        self.gbGridWorld.setTitle(_translate("MainWindow", "Grid World", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Acciones", None))
        self.btnInicializarGW.setToolTip(_translate("MainWindow", "<html><head/><body><p>Establece todos los estados del Grid World al tipo de estado por defecto manteniendo la dimensión seleccionada.</p></body></html>", None))
        self.btnInicializarGW.setText(_translate("MainWindow", "Inicializar GW", None))
        self.btnGWGenerarEstados.setText(_translate("MainWindow", "Generar estados...", None))
        self.btnGWOpciones.setToolTip(_translate("MainWindow", "Configurar Grid World.", None))
        self.btnGenEstRndRapida.setToolTip(_translate("MainWindow", "Generar estados y dimensión aleatorios.", None))
        self.label_18.setText(_translate("MainWindow", "Dimensión:", None))
        self.dwQLearning.setWindowTitle(_translate("MainWindow", "Q-Learning", None))
        self.gbQLearning.setTitle(_translate("MainWindow", "Q-Learning", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Técnica", None))
        self.gbQLMatrizQ.setTitle(_translate("MainWindow", "Matriz Q", None))
        self.lblMQFormula.setText(_translate("MainWindow", "Valor ópt. = Rec. Estado Final +", None))
        self.sbValOptimoIncremento.setToolTip(_translate("MainWindow", "<html><head/><body><p>Incremento por sobre la máxima recompensa de los estados. Este valor será sumado a la recompensa máxima para obtener el valor óptimo con el cual se inicializará la Matriz Q.</p></body></html>", None))
        self.optMQInitValOptimistas.setToolTip(_translate("MainWindow", "Inicializa la Matriz Q con valores optimistas.", None))
        self.optMQInitValOptimistas.setText(_translate("MainWindow", "Inicializar con valores optimistas", None))
        self.optMQInitEnCero.setToolTip(_translate("MainWindow", "Inicializa la Matriz Q con valores igual a 0.", None))
        self.optMQInitEnCero.setText(_translate("MainWindow", "Inicializar en cero", None))
        self.label_3.setText(_translate("MainWindow", "Cada:", None))
        self.sbCantEpisodiosDec.setToolTip(_translate("MainWindow", "<html><head/><body><p>Intervalo de episodios entre las cuales el parámetro será decrementado.</p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "Decremento:", None))
        self.sbDecrementoVal.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">Paso</span> o valor de decremento. En cada intervalo el parámetro será decrementado en un <span style=\" font-style:italic;\">paso.</span></p></body></html>", None))
        self.chkDecrementarParam.setToolTip(_translate("MainWindow", "Decrementar el parámetro que se esté utilizando.", None))
        self.chkDecrementarParam.setText(_translate("MainWindow", "Decrementar parámetro", None))
        self.lblTau.setText(_translate("MainWindow", "Tau (τ):", None))
        self.lblEpsilon.setText(_translate("MainWindow", "Epsilon (ɛ):", None))
        self.lblTecnica.setText(_translate("MainWindow", "Técnica de selección:", None))
        self.sbQLEpsilon.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\">Epsilon (</span><span style=\" font-size:9pt; font-weight:600; font-style:italic;\">ɛ</span><span style=\" font-weight:600; font-style:italic;\">)</span></p><p>Parámetro que establece la probabilidad de seleccionar una <span style=\" font-style:italic;\">acción</span> aleatoria por sobre la política óptima. Rango de valores: 0 ≤ <span style=\" font-size:9pt;\">ɛ</span> &lt; 1.</p></body></html>", None))
        self.sbQLTau.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\">Tau (</span><span style=\" font-size:9pt; font-weight:600; font-style:italic;\">τ</span><span style=\" font-weight:600; font-style:italic;\">)</span></p><p>Parámetro que establece la <span style=\" font-style:italic;\">temperatura</span>. Una <span style=\" font-style:italic;\">temperatura alta</span> causa que todas las acciones sean (casi) equiprobables. Una <span style=\" font-style:italic;\">temperatura baja</span> causa una mayor diferencia en la probabilidad de selección para las acciones que difieran en las estimaciones de sus valores.</p></body></html>", None))
        self.gbCondicionParada.setTitle(_translate("MainWindow", "Condición de parada", None))
        self.label_2.setText(_translate("MainWindow", "Cantidad de episodios:", None))
        self.sbCantidadEpisodios.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\">Cantidad de Episodios</span></p><p>Número de Episodios (Plays) a realizar durante la fase de aprendizaje (entrenamiento). Un episodio es un recorrido desde un estado dado hasta el estado <span style=\" font-style:italic;\">final.</span></p></body></html>", None))
        self.lblCantMaxIteraciones.setText(_translate("MainWindow", "Cantidad máxima:", None))
        self.sbCantMaxIteraciones.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Cantidad máxima de iteraciones</span></p><p>Establece el número máximo de iteraciones a ejecutar por episodio. Cuando este valor es alcanzado la ejecución continúa en el episodio siguiente.</p></body></html>", None))
        self.chkLimitarCantIteraciones.setToolTip(_translate("MainWindow", "Determina si se limitará la cantidad de iteraciones por cada episodio.", None))
        self.chkLimitarCantIteraciones.setText(_translate("MainWindow", "Limitar cantidad de iteraciones por episodio", None))
        self.lblMatQDiff.setText(_translate("MainWindow", "Diferencia:", None))
        self.lblMatQIntervalo.setText(_translate("MainWindow", "Calcular diferencia cada:", None))
        self.sbIntervaloDiffCalc.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Intervalo de cálculo de diferencia</span></p><p>La diferencia entre matrices se calculará cada un número dado de episodios establecidos por este valor.</p></body></html>", None))
        self.sbMatricesMinDiff.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Diferencia entre matrices Q</span></p><p align=\"center\">Establece la diferencia mínima que tiene que haber entre una Matriz Q (en t = i) y otra Matriz Q (en t = i + 1) para que se detenga la ejecución del algoritmo.</p></body></html>", None))
        self.chkQLCalcularMatDiff.setText(_translate("MainWindow", "Detener por diferencia entre matrices Q", None))
        self.lblGamma.setText(_translate("MainWindow", "Gamma (Ɣ):", None))
        self.sbQLGamma.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\">Factor de descuento</span></p><p>Cuanto más cerca de 1 se encuentre este valor mayor será el <span style=\" font-style:italic;\">peso</span> asignado a los refuerzos futuros.</p></body></html>", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Acciones", None))
        self.btnInicializarValoresQL.setToolTip(_translate("MainWindow", "Establece todos los valores de Q-Learning a los predeterminados.", None))
        self.btnInicializarValoresQL.setText(_translate("MainWindow", "Inicializar valores", None))
        self.dwEjecucion.setWindowTitle(_translate("MainWindow", "Ejecución", None))
        self.gbMatrizQ.setTitle(_translate("MainWindow", "Matriz Q", None))
        self.btnMostrarMatrizQ.setText(_translate("MainWindow", "Ver matriz...", None))
        self.btnMatrizQVerHM.setToolTip(_translate("MainWindow", "Generar y mostrar heatmap de Matriz Q", None))
        self.btnMatrizQVerHM.setText(_translate("MainWindow", "Ver heatmap...", None))
        self.gbMatrizR.setTitle(_translate("MainWindow", "Matriz R", None))
        self.btnMostrarMatrizR.setText(_translate("MainWindow", "Ver matriz...", None))
        self.btnMatrizRVerHM.setToolTip(_translate("MainWindow", "Generar y mostrar heatmap de Matriz R", None))
        self.btnMatrizRVerHM.setText(_translate("MainWindow", "Ver heatmap...", None))
        self.gbAgente.setTitle(_translate("MainWindow", "Agente", None))
        self.btnEntrenar.setText(_translate("MainWindow", "Entrenar", None))
        self.btnRecorrer.setText(_translate("MainWindow", "Explotar", None))
        self.btnPausar.setText(_translate("MainWindow", "Pausar", None))
        self.btnTerminarProceso.setText(_translate("MainWindow", "Detener", None))
        self.dwCaminoOptimo.setWindowTitle(_translate("MainWindow", "Camino óptimo", None))
        self.gbCOAcciones.setTitle(_translate("MainWindow", "Acciones", None))
        self.btnCOShowHide.setText(_translate("MainWindow", "Ocultar", None))
        self.btnCOVerDetalles.setText(_translate("MainWindow", "Ver detalles...", None))
        self.gbCOAvance.setTitle(_translate("MainWindow", "Estado a estado", None))
        self.btnCOAtras.setToolTip(_translate("MainWindow", "Mostrar estado anterior", None))
        self.btnCOAtras.setText(_translate("MainWindow", "Atrás", None))
        self.btnCOAdelante.setToolTip(_translate("MainWindow", "Mostrar siguiente estado", None))
        self.btnCOAdelante.setText(_translate("MainWindow", "Adelante", None))
        self.dwMetricas.setWindowTitle(_translate("MainWindow", "Métricas", None))
        self.gbEntrenamiento.setTitle(_translate("MainWindow", "Entrenamiento", None))
        self.gbEntExecTime.setTitle(_translate("MainWindow", "Tiempo de ejecución", None))
        self.label_13.setText(_translate("MainWindow", "Episodios:", None))
        self.lblEntExecTimeEpisodios.setText(_translate("MainWindow", "-", None))
        self.label_11.setText(_translate("MainWindow", "Iteraciones:", None))
        self.lblEntExecTimeIteraciones.setText(_translate("MainWindow", "-", None))
        self.label_15.setText(_translate("MainWindow", "Total:", None))
        self.lblEntExecTimeTotal.setText(_translate("MainWindow", "-", None))
        self.label_9.setText(_translate("MainWindow", "Iteración:", None))
        self.lblEntNroIteracion.setText(_translate("MainWindow", "-", None))
        self.label_7.setText(_translate("MainWindow", "Episodio:", None))
        self.lblEntNroEpisodio.setText(_translate("MainWindow", "-", None))
        self.label_4.setText(_translate("MainWindow", "Posición agente:", None))
        self.lblEntEstadoActual.setText(_translate("MainWindow", "-", None))
        self.label_10.setText(_translate("MainWindow", "Valor parámetro de técnica:", None))
        self.lblEntValParametro.setText(_translate("MainWindow", "-", None))
        self.label_14.setText(_translate("MainWindow", "Diferencia entre matrices:", None))
        self.lblEntDiffMatrices.setText(_translate("MainWindow", "-", None))
        self.gbRecorrido.setTitle(_translate("MainWindow", "Explotación", None))
        self.label_6.setText(_translate("MainWindow", "Posición agente:", None))
        self.lblRecEstadoActual.setText(_translate("MainWindow", "-", None))
        self.gbRecExecTime.setTitle(_translate("MainWindow", "Tiempo de ejecución", None))
        self.label_16.setText(_translate("MainWindow", "Total:", None))
        self.lblRecExecTimeTotal.setText(_translate("MainWindow", "-", None))
        self.label_17.setText(_translate("MainWindow", "Explotación:", None))
        self.lblRecExecTimeRecorrido.setText(_translate("MainWindow", "-", None))
        self.dwConfigGeneral.setWindowTitle(_translate("MainWindow", "Configuración general", None))
        self.gbGeneral.setTitle(_translate("MainWindow", "General", None))
        self.btnInicializarTodo.setToolTip(_translate("MainWindow", "Establece todos los valores de la aplicación a los predeterminados.", None))
        self.btnInicializarTodo.setText(_translate("MainWindow", "Inicializar valores", None))
        self.menuArchivo.setTitle(_translate("MainWindow", "&Archivo", None))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ay&uda", None))
        self.menuOperaciones.setTitle(_translate("MainWindow", "Agente", None))
        self.menuConfiguracion.setTitle(_translate("MainWindow", "&Configuración", None))
        self.menuGridWorld.setTitle(_translate("MainWindow", "Grid World", None))
        self.menuQLearning.setTitle(_translate("MainWindow", "Q-Learning", None))
        self.menuHeatmap.setTitle(_translate("MainWindow", "Heatmap", None))
        self.menuInterpolacion.setTitle(_translate("MainWindow", "Interpolación", None))
        self.menuAnteBloqueo.setTitle(_translate("MainWindow", "Ante bloqueo", None))
        self.menuEstadisticas.setTitle(_translate("MainWindow", "Estadísticas", None))
        self.menuPruebas.setTitle(_translate("MainWindow", "Pruebas", None))
        self.actionAppSalir.setText(_translate("MainWindow", "Salir", None))
        self.actionAcercaDe.setText(_translate("MainWindow", "Acerca de...", None))
        self.actionAgenteEntrenar.setText(_translate("MainWindow", "Entrenar", None))
        self.actionAgenteRecorrer.setText(_translate("MainWindow", "Explotar", None))
        self.actionAgenteCancelar.setText(_translate("MainWindow", "Detener", None))
        self.actionInicializarTodo.setText(_translate("MainWindow", "Inicializar todo", None))
        self.actionAgentePausar.setText(_translate("MainWindow", "Pausar", None))

import recursos_rc
